"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {api,ApiError,dateAt,dateTimeAt,messageFor,shortId} from "@/lib/api";
import {useSession} from "@/lib/session";
import {useWorkspaceEvidence} from "@/lib/use-workspace";
import {DataState} from "@/components/data-state";
import {StatusBadge} from "@/components/status-badge";
import type {DisruptionRecord,Page,ReplanPreview,RollingReplan,RunIndexItem,WhatIfImpact,WhatIfScenario} from "@/lib/types";

type ChangeKind="TRAIN_DELAY"|"FREIGHT_COUNT"|"RESOURCE_OUTAGE"|"RESTRICTION"|"ADD_REQUEST";
type EventKind="TRAIN_DELAY"|"FREIGHT_CHANGE"|"RESOURCE_OUTAGE"|"URGENT_DEFECT"|"RESTRICTION_CHANGE";
const show=(value:string)=>value.replaceAll("_"," ");
function dateInput(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?"":new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function instant(value:string){if(!value)throw new Error("Enter a dated time for this change.");const date=new Date(value);if(Number.isNaN(date.getTime()))throw new Error("Enter a valid dated time.");return date.toISOString()}
function errorText(cause:unknown){return cause instanceof Error&&!(cause instanceof ApiError)?cause.message:messageFor(cause)}
function FieldNote({children}:{children:React.ReactNode}){return <p className="quiet-note change-field-note">{children}</p>}
function JsonRow({value}:{value:Record<string,unknown>}){return <pre className="change-json">{JSON.stringify(value,null,2)}</pre>}

export default function ChangesPage(){
  const data=useWorkspaceEvidence();const {value:session}=useSession();
  const [mode,setMode]=useState<"scenario"|"replan">("scenario");
  const [error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[busy,setBusy]=useState(false);
  const [name,setName]=useState(""),[changeKind,setChangeKind]=useState<ChangeKind>("TRAIN_DELAY"),[changes,setChanges]=useState<Array<Record<string,unknown>>>([]);
  const [occupancyId,setOccupancyId]=useState(""),[delay,setDelay]=useState(10),[freightId,setFreightId]=useState(""),[forecastCount,setForecastCount]=useState(0);
  const [resourceId,setResourceId]=useState(""),[trackId,setTrackId]=useState(""),[startAt,setStartAt]=useState(""),[endAt,setEndAt]=useState("");
  const [ruleId,setRuleId]=useState(""),[restrictionType,setRestrictionType]=useState("CLOSURE"),[requestJson,setRequestJson]=useState("");
  const [scenarioId,setScenarioId]=useState<string|null>(null),[scenarioOpenId,setScenarioOpenId]=useState(""),[scenario,setScenario]=useState<WhatIfScenario|null>(null),[scenarioError,setScenarioError]=useState<string|null>(null);
  const [pendingScenario,setPendingScenario]=useState<Record<string,unknown>|null>(null);
  const [sourceRuns,setSourceRuns]=useState<RunIndexItem[]>([]),[scenarioRuns,setScenarioRuns]=useState<RunIndexItem[]>([]);
  const [sourceRevision,setSourceRevision]=useState(""),[scenarioRevision,setScenarioRevision]=useState(""),[impactId,setImpactId]=useState<string|null>(null),[impactOpenId,setImpactOpenId]=useState(""),[impact,setImpact]=useState<WhatIfImpact|null>(null);
  const [eventKind,setEventKind]=useState<EventKind>("TRAIN_DELAY"),[eventSource,setEventSource]=useState(""),[eventExternalId,setEventExternalId]=useState(""),[eventRevision,setEventRevision]=useState(1),[eventTime,setEventTime]=useState(""),[eventTracks,setEventTracks]=useState(""),[eventResources,setEventResources]=useState(""),[eventEvidence,setEventEvidence]=useState(""),[eventDescription,setEventDescription]=useState("");
  const [eventId,setEventId]=useState<string|null>(null),[event,setEvent]=useState<DisruptionRecord|null>(null),[pendingEvent,setPendingEvent]=useState<Record<string,unknown>|null>(null);
  const [preview,setPreview]=useState<ReplanPreview|null>(null),[previewError,setPreviewError]=useState<string|null>(null),[contextJson,setContextJson]=useState(""),[rollingId,setRollingId]=useState<string|null>(null),[rollingOpenId,setRollingOpenId]=useState(""),[rolling,setRolling]=useState<RollingReplan|null>(null),[pendingRolling,setPendingRolling]=useState<Record<string,unknown>|null>(null);
  const [executionCapture,setExecutionCapture]=useState<{id:string;status:string;current:boolean;payload:{blockers:string[]}}|null>(null);
  const source=data.snapshot?.scenario_id?null:data.snapshot;
  const view=source&&data.view?.snapshot.id===source.id?data.view:null;
  const canWrite=["ADMIN","PLANNER","CONTROLLER"].includes(session?.user.role??"");
  const controller=session?.user.role==="CONTROLLER";
  const revisionOptions=data.runs.flatMap(run=>run.revision_ids.map(id=>({id,run})));
  const selectedRevisionId=data.selection.revisionId??view?.selected_revision?.id??revisionOptions.find(x=>x.run.planner_type==="CP_SAT")?.id??revisionOptions[0]?.id??null;
  useEffect(()=>{setExecutionCapture(null)},[selectedRevisionId]);
  const sourceHashMatches=!!scenario&&!!source&&scenario.source_snapshot_id===source.id&&scenario.payload.source_snapshot_hash===source.content_hash;
  useEffect(()=>{const params=new URLSearchParams(window.location.search);setScenarioId(params.get("scenario_id"));setImpactId(params.get("impact_id"));setRollingId(params.get("replan_id"));if(params.has("replan_id")||params.get("mode")==="replan")setMode("replan")},[]);
  useEffect(()=>{if(!source){setSourceRuns([]);return}const controller=new AbortController();void api<Page<RunIndexItem>>(`/workspace/runs?snapshot_id=${encodeURIComponent(source.id)}&limit=100`,{signal:controller.signal}).then(x=>{if(!controller.signal.aborted)setSourceRuns(x.items)}).catch(()=>{if(!controller.signal.aborted)setSourceRuns([])});return()=>controller.abort()},[source,data.runs]);
  useEffect(()=>{if(!scenarioId){setScenario(null);return}let live=true;setScenarioError(null);
    async function read(){try{const saved=await api<WhatIfScenario>(`/what-if-scenarios/${encodeURIComponent(scenarioId!)}`);if(live){setScenario(saved);setScenarioOpenId(saved.id)}}catch(cause){if(live){setScenario(null);setScenarioError(messageFor(cause))}}}
    void read();const timer=setInterval(()=>{if(live)void read()},4000);return()=>{live=false;clearInterval(timer)};
  },[scenarioId]);
  useEffect(()=>{if(!scenario){setScenarioRuns([]);return}const controller=new AbortController();void api<Page<RunIndexItem>>(`/workspace/runs?snapshot_id=${encodeURIComponent(scenario.snapshot_id)}&limit=100`,{signal:controller.signal}).then(x=>{if(!controller.signal.aborted)setScenarioRuns(x.items)}).catch(()=>{if(!controller.signal.aborted)setScenarioRuns([])});return()=>controller.abort()},[scenario]);
  useEffect(()=>{if(!impactId){setImpact(null);return}const controller=new AbortController();void api<WhatIfImpact>(`/what-if-impacts/${encodeURIComponent(impactId)}`,{signal:controller.signal}).then(x=>{if(!controller.signal.aborted)setImpact(x)}).catch(cause=>{if(!controller.signal.aborted)setError(messageFor(cause))});return()=>controller.abort()},[impactId]);
  useEffect(()=>{if(!eventId){setEvent(null);return}const controller=new AbortController();void api<DisruptionRecord>(`/disruption-events/${encodeURIComponent(eventId)}`,{signal:controller.signal}).then(x=>{if(!controller.signal.aborted)setEvent(x)}).catch(cause=>{if(!controller.signal.aborted)setError(messageFor(cause))});return()=>controller.abort()},[eventId]);
  useEffect(()=>{if(!rollingId){setRolling(null);return}let live=true;async function read(){try{const saved=await api<RollingReplan>(`/rolling-replans/${encodeURIComponent(rollingId!)}`);if(live){setRolling(saved);setRollingOpenId(saved.id)}}catch(cause){if(live)setError(messageFor(cause))}}void read();const timer=setInterval(()=>{if(live)void read()},4000);return()=>{live=false;clearInterval(timer)}},[rollingId]);
  function urlId(key:string,id:string){const url=new URL(window.location.href);url.searchParams.set(key,id);window.history.replaceState(null,"",url.pathname+url.search)}
  function addChange(){setError(null);try{let value:Record<string,unknown>;
    if(changeKind==="TRAIN_DELAY"){if(!occupancyId||delay<1||delay>240)throw new Error("Select an occupancy and enter 1–240 delay minutes.");value={kind:changeKind,occupancy_id:occupancyId,delay_minutes:delay}}
    else if(changeKind==="FREIGHT_COUNT"){if(!freightId||forecastCount<0||forecastCount>1000)throw new Error("Select a freight forecast and enter a count from 0–1000.");value={kind:changeKind,external_id:freightId,expected_count:forecastCount}}
    else if(changeKind==="RESOURCE_OUTAGE"){if(!resourceId||!trackId)throw new Error("Select a named resource and track.");value={kind:changeKind,resource_id:resourceId,track_id:trackId,start_at:instant(startAt),end_at:instant(endAt)}}
    else if(changeKind==="RESTRICTION"){if(!trackId||!ruleId.trim())throw new Error("Select a track and provide the restriction rule ID.");value={kind:changeKind,track_ids:[trackId],start_at:instant(startAt),end_at:instant(endAt),rule_id:ruleId.trim(),restriction_type:restrictionType}}
    else {const parsed=JSON.parse(requestJson) as unknown;if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("Enter one maintenance request JSON object.");value={kind:"ADD_REQUEST",request_id:crypto.randomUUID(),data:parsed}}
    if("start_at" in value&&new Date(String(value.start_at))>=new Date(String(value.end_at)))throw new Error("The change end must follow its start.");
    setChanges(previous=>[...previous,value]);
  }catch(cause){setError(errorText(cause))}}
  async function submitScenario(body:Record<string,unknown>){if(!session)return;setBusy(true);setError(null);setNotice(null);
    try{const saved=await api<WhatIfScenario>("/what-if-scenarios",{method:"POST",csrf:session.csrf_token,body,signal:AbortSignal.timeout(20000)});
      setScenario(saved);setScenarioId(saved.id);setPendingScenario(null);setChanges([]);urlId("scenario_id",saved.id);
      setNotice(`Isolated scenario ${shortId(saved.id)} queued. Source facts and controller reservations were not changed.`);
    }catch(cause){setError(errorText(cause));if(cause instanceof ApiError&&[401,403,409,422].includes(cause.status))setPendingScenario(null);
      else setNotice("Result unconfirmed. Reopen the saved ID if known, or retry the identical request key; do not create a new scenario yet.")}
    finally{setBusy(false)}}
  async function createScenario(){if(!source||!session||!changes.length||name.trim().length<3)return;const body={idempotency_key:crypto.randomUUID(),source_snapshot_id:source.id,expected_source_hash:source.content_hash,name:name.trim(),changes};setPendingScenario(body);await submitScenario(body)}
  async function createImpact(){if(!scenario||!sourceRevision||!scenarioRevision||!session)return;setBusy(true);setError(null);
    try{const saved=await api<WhatIfImpact>(`/what-if-scenarios/${scenario.id}/impacts`,{method:"POST",csrf:session.csrf_token,body:{source_plan_revision_id:sourceRevision,scenario_plan_revision_id:scenarioRevision}});
      setImpact(saved);setImpactId(saved.id);setImpactOpenId(saved.id);urlId("impact_id",saved.id);setNotice("Input-changed impact saved. Raw deltas are not optimizer gains.");
    }catch(cause){setError(messageFor(cause))}finally{setBusy(false)}}
  async function submitEvent(body:Record<string,unknown>){if(!session)return;setBusy(true);setError(null);setNotice(null);
    try{const saved=await api<DisruptionRecord>("/disruption-events",{method:"POST",csrf:session.csrf_token,body,signal:AbortSignal.timeout(20000)});
      setEvent(saved);setEventId(saved.id);setPendingEvent(null);data.refresh();setNotice(`Event ${shortId(saved.id)} recorded. Affected snapshots are stale; source facts still need a real revision.`);
    }catch(cause){setError(errorText(cause));if(cause instanceof ApiError&&[401,403,409,422].includes(cause.status))setPendingEvent(null);
      else setNotice("Event result unconfirmed. Reopen the event ID if known or retry the exact source/external ID/revision.")}
    finally{setBusy(false)}}
  async function createEvent(){try{if(!source||!eventSource.trim()||!eventExternalId.trim()||!eventEvidence.trim()||!eventDescription.trim())throw new Error("Enter source identity, external ID, evidence reference and description.");
    const tracks=eventTracks.split(",").map(x=>x.trim()).filter(Boolean),resources=eventResources.split(",").map(x=>x.trim()).filter(Boolean);
    if(!tracks.length&&!resources.length)throw new Error("Name an affected track or resource.");
    const body={source:eventSource.trim(),external_id:eventExternalId.trim(),source_revision:eventRevision,scope:"SIMULATED",kind:eventKind,
      occurred_at:instant(eventTime),track_ids:tracks,resource_ids:resources,evidence_reference:eventEvidence.trim(),description:eventDescription.trim()};
    setPendingEvent(body);await submitEvent(body);
  }catch(cause){setError(errorText(cause))}}
  async function captureExecution(){if(!controller||!selectedRevisionId||!session)return;setBusy(true);setError(null);setNotice(null);setExecutionCapture(null);
    try{const [revision,freeze]=await Promise.all([api<{plan_hash:string}>(`/plan-revisions/${selectedRevisionId}`),api<{operational_revision:number}>(`/plan-revisions/${selectedRevisionId}/freeze-context`)]);
      const saved=await api<{id:string;status:string;current:boolean;payload:{blockers:string[]}}>(`/plan-revisions/${selectedRevisionId}/replanning-captures`,{method:'POST',csrf:session.csrf_token,body:{expected_plan_hash:revision.plan_hash,expected_operational_revision:freeze.operational_revision}});
      setExecutionCapture(saved);setNotice('Execution ledger captured. Inspect blockers before preparing replacement facts. This does not approve or queue a plan.');
    }catch(cause){setError(messageFor(cause))}finally{setBusy(false)}
  }
  async function loadPreview(){if(!selectedRevisionId)return;setPreviewError(null);setPreview(null);
    try{setPreview(await api<ReplanPreview>(`/rolling-replans/preview/${encodeURIComponent(selectedRevisionId)}`))}
    catch(cause){setPreviewError(messageFor(cause))}}
  async function submitRolling(body:Record<string,unknown>){if(!session)return;setBusy(true);setError(null);setNotice(null);
    try{const saved=await api<RollingReplan>("/rolling-replans",{method:"POST",csrf:session.csrf_token,body,signal:AbortSignal.timeout(25000)});
      setRolling(saved);setRollingId(saved.id);setPendingRolling(null);urlId("replan_id",saved.id);data.refresh();setNotice(`Replacement proposal ${shortId(saved.id)} queued. Independent validation and controller review remain required.`);
    }catch(cause){setError(errorText(cause));if(cause instanceof ApiError&&[401,403,409,422].includes(cause.status))setPendingRolling(null);
      else setNotice("Preparation result unconfirmed. Open a known replan ID or retry with the identical idempotency key.")}
    finally{setBusy(false)}}
  async function prepareRolling(){if(!controller||!preview||preview.status!=="READY"||!selectedRevisionId)return;setError(null);
    try{const declaration=JSON.parse(contextJson) as unknown;if(!declaration||typeof declaration!=="object"||Array.isArray(declaration)||"facts_hash" in declaration)throw new Error("Enter a reviewed validation-context JSON object without facts_hash. The server binds that hash.");
      const [revision,freeze]=await Promise.all([api<{id:string;plan_hash:string}>(`/plan-revisions/${selectedRevisionId}`),api<{operational_revision:number}>(`/plan-revisions/${selectedRevisionId}/freeze-context`)]);
      const fresh=await api<ReplanPreview>(`/rolling-replans/preview/${selectedRevisionId}`);
      if(fresh.status!=="READY"||fresh.base_facts_hash!==preview.base_facts_hash||fresh.batch_generation!==preview.batch_generation)throw new Error("Source facts or event batch changed. Refresh and review the preview again.");
      const body={idempotency_key:crypto.randomUUID(),source_plan_revision_id:selectedRevisionId,expected_plan_hash:revision.plan_hash,
        expected_operational_revision:freeze.operational_revision,expected_batch_generation:fresh.batch_generation,expected_base_facts_hash:fresh.base_facts_hash,validation_context:declaration};
      setPendingRolling(body);await submitRolling(body);
    }catch(cause){setError(errorText(cause));setPreview(null)}}
  const sourceCP=sourceRuns.filter(x=>x.planner_type==="CP_SAT").flatMap(x=>x.revision_ids.map(id=>({id,run:x})));
  const scenarioCP=scenarioRuns.filter(x=>x.planner_type==="CP_SAT").flatMap(x=>x.revision_ids.map(id=>({id,run:x})));
  return <div className="content-flow changes-page"><div className="page-heading"><div><span className="eyebrow">CHANGED-FACT PLANNING</span><h1>Replanning &amp; What-if</h1><p>Explore isolated alternatives or prepare a replacement after a recorded source change. These workflows have different authority and evidence.</p></div><div className="page-actions"><button className="button button-outline" onClick={()=>{data.refresh();if(mode==="replan")void loadPreview()}}>Refresh evidence</button></div></div>
    {(error||data.error)&&<div className="inline-alert" role="alert">{error??data.error}</div>}{notice&&<div className="inline-success" role="status">{notice}</div>}
    <div className="change-mode-tabs"><button className={mode==="scenario"?"selected":""} onClick={()=>setMode("scenario")}>Isolated what-if</button><button className={mode==="replan"?"selected":""} onClick={()=>setMode("replan")}>Source disruption &amp; replacement</button></div>
    <div className="planning-context panel"><label className="field">Source planning snapshot<select value={data.selection.snapshotId??""} onChange={e=>{data.selectSnapshot(e.target.value||null);setPreview(null)}}><option value="">Select source snapshot</option>{data.snapshots.filter(x=>!x.scenario_id).map(x=><option key={x.id} value={x.id}>{x.source_scope} · {dateAt(x.horizon_start)} · {shortId(x.id)}</option>)}</select></label>
      <label className="field">Source plan revision<select value={selectedRevisionId??""} disabled={!source} onChange={e=>{data.selection.selectRevision(e.target.value||null);setPreview(null)}}><option value="">Select revision</option>{revisionOptions.map(x=><option key={x.id} value={x.id}>{shortId(x.id)} · {x.run.planner_type}</option>)}</select></label>
      <div className="context-stamp"><span>Source state</span><strong>{view?.source_state??"NOT SELECTED"}</strong><small>{source?.source_scope??"Select a non-scenario snapshot"}</small></div><div className="context-stamp"><span>Authority</span><strong>{mode==="scenario"?"Isolated simulation":"Software proposal"}</strong><small>External railway authorization remains separate</small></div></div>
    {mode==="scenario"?<>
      <div className="change-banner isolated"><strong>Isolated simulation only</strong><span>Changes are copied into a scenario snapshot. Source facts, controller decisions and reservations remain untouched. Scenario plans cannot be approved.</span></div>
      <div className="change-main-grid"><section className="panel"><div className="panel-header"><div><h2>Define alternative facts</h2><p>One to twenty explicit changes, checked against the selected current source</p></div></div><div className="change-form">
        <label className="field">Scenario name<input value={name} maxLength={120} onChange={e=>setName(e.target.value)} placeholder="Describe the operational question"/></label>
        <label className="field">Change type<select value={changeKind} onChange={e=>setChangeKind(e.target.value as ChangeKind)}>{(["TRAIN_DELAY","FREIGHT_COUNT","RESOURCE_OUTAGE","RESTRICTION","ADD_REQUEST"] as ChangeKind[]).map(x=><option key={x} value={x}>{show(x)}</option>)}</select></label>
        {changeKind==="TRAIN_DELAY"&&<><label className="field">Saved train occupancy<select value={occupancyId} onChange={e=>setOccupancyId(e.target.value)}><option value="">Select train / track / time</option>{view?.facts.occupancy.map(x=><option key={x.id} value={x.id}>{x.train_id} · {x.track_id} · {dateTimeAt(x.enter_at)} · {shortId(x.id)}</option>)}</select></label><label className="field">Delay minutes<input type="number" min={1} max={240} value={delay} onChange={e=>setDelay(Number(e.target.value))}/></label></>}
        {changeKind==="FREIGHT_COUNT"&&<><label className="field">Saved freight forecast<select value={freightId} onChange={e=>setFreightId(e.target.value)}><option value="">Select forecast</option>{view?.facts.freight.map(x=><option key={x.id} value={x.external_id}>{x.external_id} · {x.track_id} · expected {x.expected_count}</option>)}</select></label><label className="field">New expected count<input type="number" min={0} max={1000} value={forecastCount} onChange={e=>setForecastCount(Number(e.target.value))}/></label></>}
        {changeKind==="RESOURCE_OUTAGE"&&<label className="field">Named resource<select value={resourceId} onChange={e=>setResourceId(e.target.value)}><option value="">Select resource</option>{view?.facts.resources?.map((x,i)=><option key={String(x.id??i)} value={String(x.id)}>{String(x.id)} · {String(x.type??x.resource_type??"resource")}</option>)}</select></label>}
        {(["RESOURCE_OUTAGE","RESTRICTION"] as ChangeKind[]).includes(changeKind)&&<><label className="field">Affected track<select value={trackId} onChange={e=>setTrackId(e.target.value)}><option value="">Select track</option>{source?.track_ids.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="field">Start (browser local time)<input type="datetime-local" value={startAt} min={source?dateInput(source.horizon_start):undefined} max={source?dateInput(source.horizon_end):undefined} onChange={e=>setStartAt(e.target.value)}/></label><label className="field">End (browser local time)<input type="datetime-local" value={endAt} onChange={e=>setEndAt(e.target.value)}/></label></>}
        {changeKind==="RESTRICTION"&&<><label className="field">Rule reference<input value={ruleId} onChange={e=>setRuleId(e.target.value)} placeholder="Configured rule ID"/></label><label className="field">Restriction type<select value={restrictionType} onChange={e=>setRestrictionType(e.target.value)}><option value="CLOSURE">Closure</option><option value="WORK_PROHIBITED">Work prohibited</option><option value="ISOLATION_UNAVAILABLE">Isolation unavailable</option></select></label></>}
        {changeKind==="ADD_REQUEST"&&<><label className="field change-wide">New SIMULATED maintenance request JSON<textarea rows={9} value={requestJson} onChange={e=>setRequestJson(e.target.value)} placeholder="Paste the full MaintenanceRequest payload for a new asset work item"/></label><FieldNote>The backend validates the complete request, asset, department, footprint and access requirements. A new scenario-only request ID is generated on Add.</FieldNote></>}
        <div className="change-form-actions"><button className="button button-outline" disabled={!view||changes.length>=20} onClick={addChange}>Add declared change</button><button className="button button-primary" disabled={!source||view?.source_state!=="CURRENT"||!canWrite||name.trim().length<3||!changes.length||busy||!!pendingScenario} onClick={()=>void createScenario()}>{busy?"Queuing…":"Run isolated scenario"}</button></div>
        {pendingScenario&&<div className="review-pending"><strong>Scenario result unconfirmed</strong><span>Idempotency key {shortId(String(pendingScenario.idempotency_key))}</span><button className="button button-outline" disabled={busy} onClick={()=>void submitScenario(pendingScenario)}>Retry exact request</button></div>}
      </div></section><aside className="panel"><div className="panel-header"><div><h2>Changes to apply</h2><p>Inputs only; no schedule has been calculated yet</p></div><span>{changes.length} / 20</span></div><div className="change-list">{changes.length?changes.map((x,i)=><div className="change-input-card" key={i}><div><strong>{show(String(x.kind))}</strong><button onClick={()=>setChanges(previous=>previous.filter((_,j)=>j!==i))}>Remove</button></div><JsonRow value={x}/></div>):<DataState title="No change added" detail="Choose a saved source fact and add at least one explicit scenario change."/>}</div></aside></div>
      <section className="panel"><div className="panel-header"><div><h2>Scenario result</h2><p>Open a saved ID or inspect the latest queued scenario</p></div><StatusBadge value={scenario?.optimized_run.status??"NOT_RUN"}/></div><div className="change-open"><label className="field">Scenario ID<input value={scenarioOpenId} onChange={e=>setScenarioOpenId(e.target.value.trim())} placeholder="Saved scenario UUID"/></label><button className="button button-outline" disabled={!scenarioOpenId} onClick={()=>{setScenarioId(scenarioOpenId);urlId("scenario_id",scenarioOpenId)}}>Open</button></div>
        {scenarioError&&<div className="inline-alert">{scenarioError}</div>}{scenario?<div className="change-result"><div className="change-result-head"><strong>{scenario.payload.name}</strong><span>Scenario {shortId(scenario.id)} · source {shortId(scenario.source_snapshot_id)}</span><StatusBadge value={scenario.approval_permitted?"REVIEWABLE":"APPROVAL_FORBIDDEN"}/></div>
          <div className="change-metrics"><div><span>Baseline run</span><StatusBadge value={scenario.baseline_run.status}/><small>{shortId(scenario.baseline_run.id)}</small></div><div><span>CP-SAT run</span><StatusBadge value={scenario.optimized_run.status}/><small>{shortId(scenario.optimized_run.id)}</small></div><div><span>Declared changes</span><strong>{scenario.payload.changes.length}</strong></div><div><span>Candidate evidence</span><strong>{scenario.payload.candidate_count?.candidates??"Not recorded"}</strong></div></div>
          <div className="change-records"><strong>Saved input changes</strong>{scenario.payload.changes.map((x,i)=><JsonRow key={i} value={x}/>)}</div>
          {!sourceHashMatches&&<div className="inline-note">The selected source does not match this scenario. Select the source snapshot before interpreting differences.</div>}
          <div className="change-links"><button className="button button-outline" onClick={()=>data.selectSnapshot(scenario.source_snapshot_id)}>Inspect source snapshot</button><button className="button button-outline" onClick={()=>data.selectSnapshot(scenario.snapshot_id)}>Inspect isolated snapshot</button><Link href="/evaluation">Same-scenario baseline comparison →</Link></div>
        </div>:<DataState title="No scenario selected" detail="Create an isolated alternative or open a saved scenario ID."/>}</section>
      <section className="panel"><div className="panel-header"><div><h2>Source-versus-scenario impact</h2><p>Different input facts: raw deltas only, never optimizer improvement</p></div></div><div className="change-impact-controls"><label className="field">Source CP-SAT revision<select value={sourceRevision} onChange={e=>setSourceRevision(e.target.value)}><option value="">Select validated source revision</option>{sourceCP.map(x=><option key={x.id} value={x.id}>{shortId(x.id)} · {x.run.job_status}</option>)}</select></label><label className="field">Scenario CP-SAT revision<select value={scenarioRevision} onChange={e=>setScenarioRevision(e.target.value)}><option value="">Select validated scenario revision</option>{scenarioCP.map(x=><option key={x.id} value={x.id}>{shortId(x.id)} · {x.run.job_status}</option>)}</select></label><button className="button button-primary" disabled={!scenario||!sourceHashMatches||!sourceRevision||!scenarioRevision||busy||!canWrite} onClick={()=>void createImpact()}>Save impact</button><label className="field">Open impact ID<input value={impactOpenId} onChange={e=>setImpactOpenId(e.target.value.trim())} placeholder="Saved impact UUID"/></label><button className="button button-outline" disabled={!impactOpenId} onClick={()=>{setImpactId(impactOpenId);urlId("impact_id",impactOpenId)}}>Open</button></div>
        {impact&&<div className="change-impact"><div className="change-banner isolated"><strong>Input-changed sensitivity</strong><span>Source and scenario use different facts. These values cannot establish optimizer gains, completed work or measured train delay.</span></div><div className="change-table-scroll"><table className="change-table"><thead><tr><th>Measure</th><th>Source</th><th>Scenario</th><th>Raw delta</th><th>Unit</th></tr></thead><tbody>{Object.entries(impact.content.observed_differences).map(([key,x])=><tr key={key}><th>{show(key)}</th><td>{x.source??"N/A"}</td><td>{x.scenario??"N/A"}</td><td>{x.raw_delta??"N/A"}</td><td>{show(x.unit)}</td></tr>)}</tbody></table></div><p className="quiet-note">Impact {shortId(impact.id)} · {impact.content.claim_scope} · hash {shortId(impact.content_hash)}</p></div>}
      </section>
    </>:<>
      <div className="change-banner operational"><strong>Changed-source replacement</strong><span>Recording an event marks affected proposals stale. Update the actual source record separately; only reconciled changes may enter a new planning snapshot. A controller still reviews the validated replacement.</span></div>
      <div className="change-main-grid"><section className="panel"><div className="panel-header"><div><h2>Record SIMULATED disruption</h2><p>The event is immutable and does not change timetable, freight, resources or requests by itself</p></div></div><div className="change-form">
        <label className="field">Event kind<select value={eventKind} onChange={e=>setEventKind(e.target.value as EventKind)}>{(["TRAIN_DELAY","FREIGHT_CHANGE","RESOURCE_OUTAGE","URGENT_DEFECT","RESTRICTION_CHANGE"] as EventKind[]).map(x=><option value={x} key={x}>{show(x)}</option>)}</select></label><label className="field">Source system / recorder<input value={eventSource} onChange={e=>setEventSource(e.target.value)} placeholder="Named simulated source"/></label>
        <label className="field">External event ID<input value={eventExternalId} onChange={e=>setEventExternalId(e.target.value)} placeholder="Stable source event identity"/></label><label className="field">Source revision<input type="number" min={1} value={eventRevision} onChange={e=>setEventRevision(Number(e.target.value))}/></label>
        <label className="field">Occurred (browser local time)<input type="datetime-local" value={eventTime} onChange={e=>setEventTime(e.target.value)}/></label><label className="field">Affected tracks, comma-separated<input value={eventTracks} onChange={e=>setEventTracks(e.target.value)} placeholder={source?.track_ids.join(", ")??"Track IDs"}/></label><label className="field">Affected resource IDs, comma-separated<input value={eventResources} onChange={e=>setEventResources(e.target.value)} placeholder="Optional named resource IDs"/></label>
        <label className="field">Evidence reference<input value={eventEvidence} onChange={e=>setEventEvidence(e.target.value)} placeholder="Source evidence or fixture reference"/></label><label className="field change-wide">Description<textarea rows={3} value={eventDescription} onChange={e=>setEventDescription(e.target.value)} placeholder="What changed and how it was observed"/></label>
        <div className="change-form-actions"><button className="button button-primary" disabled={!source||!canWrite||busy||!!pendingEvent} onClick={()=>void createEvent()}>{busy?"Recording…":"Record event"}</button></div>
        {pendingEvent&&<div className="review-pending"><strong>Event result unconfirmed</strong><span>{String(pendingEvent.source)} / {String(pendingEvent.external_id)} / r{String(pendingEvent.source_revision)}</span><button className="button button-outline" disabled={busy} onClick={()=>void submitEvent(pendingEvent)}>Retry exact event</button></div>}
      </div></section><aside className="panel"><div className="panel-header"><div><h2>Event and source reconciliation</h2><p>Unknown or unchanged source facts block the replan</p></div></div><div className="change-side-body">{event?<><div className="change-record"><strong>{show(event.kind)} · {shortId(event.id)}</strong><StatusBadge value={event.result.status}/><span>{dateTimeAt(event.occurred_at)} · scope {event.scope}</span><span>Invalidated snapshots: {event.result.invalidated_snapshot_ids.length}</span><span>Source facts applied: {event.result.source_facts_applied?"Yes":"No"}</span><span>Batch generation {event.result.batch_generation}; ready {dateTimeAt(event.result.ready_at)}</span></div><JsonRow value={event.payload}/></>:<DataState title="No event recorded here" detail="Existing events can still be assessed using the preview for a selected source plan."/>}
        <button className="button button-outline" disabled={!selectedRevisionId} onClick={()=>void loadPreview()}>Check changed-source preview</button>{previewError&&<div className="inline-alert">{previewError}</div>}
        {preview&&<><div className="change-record"><strong>Preview · source {shortId(preview.source_plan_revision_id)}</strong><StatusBadge value={preview.status}/><span>Batch generation {preview.batch_generation} · facts hash {shortId(preview.base_facts_hash)}</span>{preview.blockers.map(x=><small key={x}>{show(x)}</small>)}</div>{preview.events.map(x=><div className="change-record" key={x.event_id}><strong>{show(x.kind)} · {shortId(x.event_id)}</strong><StatusBadge value={x.status}/><span>{x.matches.length} changed source record(s) matched</span>{x.matches.map((item,i)=><JsonRow key={i} value={item}/>)}</div>)}</>}
      </div></aside></div>
      <section className="panel"><div className="panel-header"><div><h2>Capture execution for replacement planning</h2><p>CONTROLLER only. Preserves completed work, remaining-work assessments and current commitments.</p></div></div><div className="change-side-body"><button className="button button-outline" disabled={!controller||!selectedRevisionId||busy} onClick={()=>void captureExecution()}>Capture current execution ledger</button>{!controller&&<p>Ask the controller to capture the approved source revision; planners cannot create execution captures.</p>}{executionCapture&&<div className="change-record"><strong>Capture {shortId(executionCapture.id)}</strong><StatusBadge value={executionCapture.status}/><span>Current when returned: {String(executionCapture.current)}</span>{executionCapture.payload.blockers.map(item=><small key={item}>{show(item)}</small>)}{executionCapture.status==='CAPTURED'&&executionCapture.current&&<Link href={`/planning?replanning_capture_id=${encodeURIComponent(executionCapture.id)}`}>Inspect capture in snapshot preparation →</Link>}<p>Planner handoff: use this capture ID in the snapshot form. Replacement solving still requires a reconciled changed-source preview and fresh declarations below. Do not invent an urgent-defect event for routine demand.</p></div>}</div></section>
      <section className="panel"><div className="panel-header"><div><h2>Prepare replacement proposal</h2><p>CONTROLLER only · fresh source declaration and exact preview hashes required</p></div></div><div className="change-prepare"><div><p>After source facts are updated and every event reconciles, provide a newly reviewed SIMULATED validation context. Do not copy expired coverage as current evidence. The server binds the new facts hash.</p><label className="field">Reviewed validation context JSON (without facts_hash)<textarea rows={8} value={contextJson} onChange={e=>setContextJson(e.target.value)} placeholder="Full fresh coverage, COA semantics, clearance, freight and commitment declarations"/></label><button className="button button-primary" disabled={!controller||preview?.status!=="READY"||!contextJson.trim()||busy||!!pendingRolling} onClick={()=>void prepareRolling()}>Prepare rolling replan</button>{!controller&&<FieldNote>Sign in with a provisioned CONTROLLER role to prepare a changed-source replacement.</FieldNote>}{pendingRolling&&<div className="review-pending"><strong>Preparation result unconfirmed</strong><button className="button button-outline" disabled={busy} onClick={()=>void submitRolling(pendingRolling)}>Retry exact request</button></div>}</div><div><label className="field">Open prepared replan ID<input value={rollingOpenId} onChange={e=>setRollingOpenId(e.target.value.trim())} placeholder="Saved replan UUID"/></label><button className="button button-outline" disabled={!rollingOpenId} onClick={()=>{setRollingId(rollingOpenId);urlId("replan_id",rollingOpenId)}}>Open saved replan</button>{rolling&&<div className="change-record"><strong>Replacement {shortId(rolling.id)}</strong><span>Snapshot {shortId(rolling.snapshot_id)} · capture {shortId(rolling.capture_id)}</span><span>Baseline <StatusBadge value={rolling.baseline_run.status}/></span><span>CP-SAT <StatusBadge value={rolling.optimized_run.status}/></span><span>Controller approval: {rolling.payload.controller_approval}</span><span>Source facts hash {shortId(rolling.payload.base_facts_hash)}</span><button className="button button-outline" onClick={()=>data.selectSnapshot(rolling.snapshot_id)}>Inspect replacement snapshot</button><Link href="/review">Validate and review saved revision →</Link></div>}</div></div></section>
    </>}
    <p className="planning-disclaimer">R-MAPS never grants a railway traffic or power block. Planned work is not completed work; scenario results cannot create controller decisions or reservations.</p>
  </div>;
}
