"use client";

import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {api,dateAt,dateTimeAt,messageFor,shortId,timeAt} from "@/lib/api";
import {useSession} from "@/lib/session";
import {useWorkspaceEvidence} from "@/lib/use-workspace";
import {DataState} from "@/components/data-state";
import {DepartmentBadge,StatusBadge} from "@/components/status-badge";
import {TimeTrackTimeline} from "@/components/time-track-timeline";
import type {Focus} from "@/lib/timeline";
import {canOpenPage,roleDashboard} from "@/lib/role-workspace";
import type {MaintenanceRequest,Page} from "@/lib/types";
import type {Candidate,Department,ReportArtifactIndex} from "@/lib/types";

const label=(value:string)=>value.replaceAll("_"," ");
function Tile({labelText,value,detail,status}:{labelText:string;value:React.ReactNode;detail:string;status?:string}){return <div className="dashboard-tile"><span>{labelText}</span><strong>{value}</strong><small>{detail}</small>{status&&<StatusBadge value={status}/>}</div>}

function PlanningDashboard(){
  const data=useWorkspaceEvidence();const {value:session}=useSession();const router=useRouter();const revisionId=data.selection.revisionId;
  const [report,setReport]=useState<ReportArtifactIndex|null>(null),[reportError,setReportError]=useState<string|null>(null),[focus,setFocus]=useState<Focus|null>(null),[version,setVersion]=useState(0);
  const revisionOptions=data.runs.flatMap(run=>run.revision_ids.map(id=>({id,run})));
  useEffect(()=>{setReport(null);setReportError(null);if(!revisionId)return;let live=true;void api<ReportArtifactIndex>(`/workspace/report-artifacts?plan_revision_id=${encodeURIComponent(revisionId)}`).then(value=>{if(live)setReport(value)}).catch(cause=>{if(live)setReportError(messageFor(cause))});return()=>{live=false}},[revisionId,version]);
  const view=data.view?.selected_revision?.id===revisionId?data.view:null;
  const assignments=view?.selected_revision?.content.assignments??[];
  const deferred=view?.selected_revision?.content.deferred??[];
  const scheduledRequests=new Set(assignments.flatMap(item=>item.request_ids));
  const mandatory=view?.demands.filter(item=>item.request.mandatory)??[];
  const ready=view?.demands.filter(item=>item.readiness.status==="READY")??[];
  const highPriority=view?.demands.filter(item=>["HIGH","CRITICAL"].includes(item.priority?.priority_band??""))??[];
  const windows=view?.availability.flatMap(item=>item.result.windows??[])??[];
  const latestDecision=report?.decisions[0]??null,latestValidation=report?.validations[0]??null;
  const departments=useMemo(()=>{const counts:Record<Department,number>={ENGINEERING:0,TRD:0,SNT:0};view?.demands.forEach(item=>counts[item.request.department]++);return counts},[view]);
  const totalDemand=view?.demands.length??0;
  const upcoming=[...assignments].sort((a,b)=>Date.parse(a.possession_start)-Date.parse(b.possession_start));
  const attention=view?[...new Set([...view.current_blockers,...view.demands.flatMap(item=>item.readiness.status==="NOT_READY"?item.readiness.reasons:[])])]:[];
  const selected=focus?(() => {if(!view)return null;const plan=assignments.find(x=>focus.kind==="assignment"&&x.id===focus.id);if(plan)return {title:`Proposed block ${shortId(plan.id)}`,detail:`${plan.track_ids.join(", ")} · ${dateTimeAt(plan.possession_start)}–${timeAt(plan.possession_end)} · ${plan.request_ids.length} request(s)`};const occupancy=view.facts.occupancy.find(x=>focus.kind==="train"&&x.id===focus.id);if(occupancy)return {title:`Train ${occupancy.train_id}`,detail:`${occupancy.track_id} · ${dateTimeAt(occupancy.enter_at)}–${timeAt(occupancy.exit_at)}`};const window=windows.find(x=>focus.kind==="window"&&x.id===focus.id);if(window)return {title:`Capacity window ${shortId(window.id)}`,detail:`${window.track_ids.join(", ")} · ${dateTimeAt(window.start_at)}–${timeAt(window.end_at)} · ${window.usable_minutes} minutes`};return {title:`${label(focus.kind)} ${shortId(focus.id)}`,detail:"Open the corresponding workspace for complete saved evidence."}})():null;
  const staff=session?.user.role!=="DEPARTMENT";
  const role=session?.user.role;
  const dashboard=roleDashboard[role??""]??roleDashboard.PLANNER;
  return <div className="content-flow dashboard-page"><div className="page-heading"><div><span className="eyebrow">INTEGRATED MAINTENANCE PLANNING · CURRENT SELECTED CASE</span><h1>{dashboard.title}</h1><p>{dashboard.detail}</p></div><div className="page-actions"><button type="button" className="button button-outline" onClick={()=>{data.refresh();setVersion(x=>x+1)}}>Refresh current evidence</button><Link className="button button-primary" href={dashboard.href}>{dashboard.action}</Link></div></div>
    {!staff&&<div className="inline-note">Department users submit and maintain work requirements in the Maintenance screen. Cross-department planning summaries require a planning, controller, audit or administrator role.</div>}
    {(data.error||reportError)&&staff&&<div className="inline-alert" role="alert">{data.error??reportError}</div>}
    {staff&&<div className="planning-context panel"><label className="field">Planning snapshot<select value={data.selection.snapshotId??""} onChange={e=>data.selectSnapshot(e.target.value||null)}><option value="">Select a snapshot</option>{data.snapshots.map(x=><option key={x.id} value={x.id}>{x.source_scope} · {dateAt(x.horizon_start)} · {shortId(x.id)}</option>)}</select></label><label className="field">Proposal revision<select value={revisionId??""} disabled={!data.snapshot} onChange={e=>data.selection.selectRevision(e.target.value||null)}><option value="">Select a saved proposal</option>{revisionOptions.map(({id,run})=><option key={id} value={id}>{run.planner_type} · {shortId(id)} · {run.job_status}</option>)}</select></label><div className="context-stamp"><span>Planning horizon</span><strong>{data.snapshot?`${dateAt(data.snapshot.horizon_start)}–${dateAt(data.snapshot.horizon_end)}`:"Not selected"}</strong><small>{data.snapshot?.track_ids.join(", ")??"Choose a saved case"}</small></div><div className="context-stamp"><span>Signed-in responsibility</span><strong>{session?.user.role??"Unknown"}</strong><small>Railway operating authorization remains external</small></div></div>}
    {!staff?<section className="panel"><DataState title="Department maintenance workspace" detail="Create, revise and track your department requirements without exposing cross-department planning evidence." action="Open Maintenance" onAction={()=>router.push("/maintenance")}/></section>:!data.snapshot||!revisionId?<section className="dashboard-empty-grid"><div className="panel"><DataState title="Select a saved planning case" detail="The dashboard will not combine the latest values from unrelated snapshots or plan revisions."/></div><div className="panel dashboard-case-list"><div className="panel-header"><div><h2>Available snapshots</h2><p>Choose one explicit immutable planning state</p></div></div>{data.snapshots.slice(0,6).map(item=><button key={item.id} type="button" onClick={()=>data.selectSnapshot(item.id)}><StatusBadge value={item.source_scope}/><span><strong>{dateAt(item.horizon_start)}</strong><small>{item.track_ids.join(", ")} · {shortId(item.id)}</small></span></button>)}</div></section>:!view?<section className="panel"><DataState title={data.viewLoading?"Loading integrated case":"Dashboard case unavailable"} detail={data.viewLoading?"Reading the exact snapshot, proposal, validation and report index…":"Refresh or select another matching proposal revision."}/></section>:<>
      <section className="dashboard-state-banner panel"><div><span>Source state</span><StatusBadge value={view.source_state}/><small>{view.current_blockers.length?`${view.current_blockers.length} current blocker(s)`:"Current against declared source facts"}</small></div><div><span>Independent validation</span><StatusBadge value={view.validation?.status??latestValidation?.status??"NOT_RUN"}/><small>{view.validation?.usable_for_review?"Currently usable for review":"Not currently usable for approval"}</small></div><div><span>Controller decision</span><StatusBadge value={report?latestDecision?.action??"NO_DECISION":"LOADING_EVIDENCE"}/><small>{latestDecision?`${latestDecision.scope} · ${dateTimeAt(latestDecision.created_at)}`:report?"Human decision not recorded":"Reading decision history"}</small></div><div><span>Authority</span><strong>Software proposal only</strong><small>No line, power or disconnection authority issued</small></div></section>
      <section className="dashboard-tiles panel"><Tile labelText="Maintenance demand" value={totalDemand} detail={`${mandatory.length} mandatory · ${highPriority.length} high/critical`}/><Tile labelText="Proposed coverage" value={`${scheduledRequests.size}/${totalDemand}`} detail={`${assignments.length} possession block(s) · ${deferred.length} deferred`}/><Tile labelText="Work readiness" value={`${ready.length}/${totalDemand}`} detail="Selected proposal context only"/><Tile labelText="Capacity evidence" value={windows.length} detail={`${view.availability.length} saved availability computation(s)`}/><Tile labelText="Execution observations" value={report?report.execution.length:"N/A"} detail={report?"Observed records; planned work excluded":"Reading saved execution evidence"}/><Tile labelText="Validation checks" value={view.validation?.result.checks_performed??"N/A"} detail={view.validation?.result.validator_version??"No current validation"}/></section>
      <div className="dashboard-main-grid"><section className="dashboard-timeline"><TimeTrackTimeline view={view} focus={focus} onFocus={setFocus} title="Corridor planning situation" layers={["train","freight","restriction","commitment","released","capacity","proposal"]}/>{selected&&<div className="dashboard-focus panel"><strong>{selected.title}</strong><span>{selected.detail}</span></div>}</section><aside className="dashboard-side"><section className="panel"><div className="panel-header"><div><h2>Department demand</h2><p>Requests in this snapshot</p></div><strong>{totalDemand}</strong></div><div className="dashboard-departments">{(Object.entries(departments) as [Department,number][]).map(([department,count])=><div key={department}><DepartmentBadge department={department}/><span><i style={{width:`${totalDemand?100*count/totalDemand:0}%`}}/></span><strong>{count}</strong></div>)}</div></section><section className="panel"><div className="panel-header"><div><h2>Attention required</h2><p>Current blockers and unready evidence</p></div><StatusBadge value={attention.length?"ATTENTION":"CLEAR"}/></div><div className="dashboard-attention">{attention.length?attention.slice(0,8).map(item=><span key={item}>{label(item)}</span>):<p>No current blocker is reported for the selected workspace. This does not grant railway authority.</p>}{attention.length>8&&<small>+ {attention.length-8} additional blockers in Validation</small>}</div><Link className="dashboard-panel-link" href="/validation">Open Validation Center →</Link></section></aside></div>
      <div className="dashboard-lower"><section className="panel"><div className="panel-header"><div><h2>Proposed blocks</h2><p>Upcoming saved assignments; planning proposals only</p></div><Link href="/schedules">Weekly / Monthly →</Link></div><div className="dashboard-blocks">{upcoming.length?upcoming.slice(0,6).map((item:Candidate)=><article key={item.id}><div><StatusBadge value={item.request_ids.length>1?"INTEGRATED":"SINGLE"}/><strong>{dateTimeAt(item.possession_start)}–{timeAt(item.possession_end)}</strong></div><span>{item.track_ids.join(", ")} · {item.request_ids.length} request(s) · {item.allocations.length} resource allocation(s)</span><div>{item.tasks.map(task=><DepartmentBadge key={task.request_id} department={task.department}/>)}</div></article>):<DataState title="No proposed blocks" detail="An empty plan remains visible; no block is inferred."/>}</div></section><section className="panel"><div className="panel-header"><div><h2>Decision workflow</h2><p>Evidence stage for the selected proposal</p></div></div><div className="dashboard-workflow"><div><span>1</span><strong>Planning state</strong><StatusBadge value={view.source_state}/></div><div><span>2</span><strong>Plan materialized</strong><StatusBadge value={view.selected_revision?"SAVED":"MISSING"}/></div><div><span>3</span><strong>Independent validation</strong><StatusBadge value={view.validation?.status??"NOT_RUN"}/></div><div><span>4</span><strong>Controller decision</strong><StatusBadge value={report?latestDecision?.action??"PENDING":"LOADING_EVIDENCE"}/></div><div><span>5</span><strong>Observed execution</strong><StatusBadge value={report?report.execution.length?"RECORDED":"NOT_RECORDED":"LOADING_EVIDENCE"}/></div></div><div className="dashboard-actions"><Link href="/review">Controller Review</Link>{canOpenPage(role,"/execution")&&<Link href="/execution">Execution &amp; Handback</Link>}<Link href="/reports">Reports &amp; Audit</Link></div></section></div>
    </>}
  </div>;
}

function DepartmentDashboard(){
  const {value:session}=useSession();
  const [rows,setRows]=useState<MaintenanceRequest[]>([]),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError(null);
    void (async()=>{const items:MaintenanceRequest[]=[];let offset:number|null=0;
      while(offset!==null){const result:Page<MaintenanceRequest>=await api<Page<MaintenanceRequest>>(`/maintenance-requests?limit=200&offset=${offset}`,{signal:controller.signal});items.push(...result.items);offset=result.next_offset??null;}
      if(!controller.signal.aborted)setRows(items);
    })().catch(cause=>{if(!controller.signal.aborted){setRows([]);setError(messageFor(cause))}}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});
    return()=>controller.abort();
  },[session?.user.id,version]);
  return <div className="content-flow dashboard-page"><div className="page-heading"><div><span className="eyebrow">{session?.user.department?.replaceAll('_',' ')} · MAINTENANCE DEMAND</span><h1>Department Maintenance Desk</h1><p>Raise requirements, review their recorded lifecycle and supply known work prerequisites.</p></div><div className="page-actions"><button className="button button-outline" onClick={()=>setVersion(x=>x+1)}>Refresh requests</button><Link className="button button-primary" href="/maintenance">Open Maintenance Demand</Link></div></div>
    {error&&<div className="inline-alert" role="alert">{error}</div>}
    {loading?<section className="panel"><DataState title="Loading department requests" detail="Reading your department’s saved maintenance requirements."/></section>:error?<section className="panel"><DataState title="Requests unavailable" detail="Restore API access and refresh; no counts are inferred."/></section>:<><section className="dashboard-tiles panel"><Tile labelText="Department requests" value={rows.length} detail="All saved department requests"/><Tile labelText="Raised" value={rows.filter(x=>x.status==='RAISED').length} detail="Recorded lifecycle state"/><Tile labelText="Pending planning" value={rows.filter(x=>x.status==='PENDING_PLANNING').length} detail="Submitted requirements"/><Tile labelText="Mandatory" value={rows.filter(x=>x.data.mandatory).length} detail="Demand flag; not completed work"/></section><section className="panel"><div className="panel-header"><div><h2>Recent maintenance requirements</h2><p>Saved request records; execution completion is recorded separately</p></div></div><div className="dashboard-blocks">{rows.length?rows.slice(-6).reverse().map(row=><article key={row.id}><div><strong>{row.data.issue_type}</strong><StatusBadge value={row.status}/></div><span>{row.data.asset_id} · {row.data.footprint.join(', ')} · {row.data.work_minutes} min work</span><small>Deadline {dateTimeAt(row.data.deadline_at)} · Revision {row.revision}</small></article>):<DataState title="No department requests" detail="Open Maintenance Demand and add a clearly labeled simulated requirement."/>}</div></section></>}
    <section className="panel"><div className="panel-header"><div><h2>Your workflow</h2><p>Submit demand and prerequisites; the planner schedules and the controller decides.</p></div><Link href="/data-readiness">Department imports →</Link></div></section></div>;
}
function AdministrationDashboard(){return <div className="content-flow"><div className="page-heading"><div><span className="eyebrow">CONFIGURATION & SERVICE OVERSIGHT</span><h1>Administration Dashboard</h1><p>Manage configuration and inspect actual readiness through the dedicated system screens.</p></div></div><section className="panel"><div className="panel-header"><h2>Administration tools</h2></div><div className="dashboard-actions"><Link href="/admin">Network & Rules</Link><Link href="/data-readiness">Data Readiness</Link><Link href="/system">System Health</Link><Link href="/reports">Reports & Audit</Link></div></section></div>}
export default function DashboardPage(){const {value:session}=useSession();return session?.user.role==='DEPARTMENT'?<DepartmentDashboard/>:session?.user.role==='ADMIN'?<AdministrationDashboard/>:<PlanningDashboard/>;}
