"use client";

import {FormEvent,useEffect,useState} from "react";
import {api,dateTimeAt,messageFor,shortId} from "@/lib/api";
import {useSession} from "@/lib/session";
import {DataState} from "@/components/data-state";
import {StatusBadge} from "@/components/status-badge";
import type {Page} from "@/lib/types";

type Kind="station"|"section"|"track"|"asset"|"isolation"|"restriction";
type NetworkEntity={id:string;kind:Kind;revision:number;[key:string]:unknown};
type Resource={id:string;resource_type:string;department:string|null;available_start:string;available_end:string;source_mode:string};
type Rule={id:string;kind:"RESOURCE_PROFILE"|"POLICY";key:string;revision:number;data:Record<string,unknown>};
const kinds:Kind[]=["station","section","track","asset","isolation","restriction"];
const schemas:Record<Kind,string>={
  station:"name",
  section:"from_station, to_station, distance_km",
  track:"section_id, direction (UP/DOWN/BOTH), status (OPEN/CLOSED), electrified",
  asset:"department (ENGINEERING/TRD/SNT), asset_type, footprint[]",
  isolation:"footprint[] of track IDs",
  restriction:"footprint[] of track IDs, start, end (timezone-aware), rule_id, type (CLOSURE/WORK_PROHIBITED/ISOLATION_UNAVAILABLE)",
};
const label=(value:string)=>value.replaceAll("_"," ");
function jsonObject(source:string):Record<string,unknown>{
  let parsed:unknown;try{parsed=JSON.parse(source)}catch{throw new Error("Enter valid JSON.")}
  if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("Enter one JSON object.");
  return parsed as Record<string,unknown>;
}

function NetworkPanel({canWrite,csrf}:{canWrite:boolean;csrf:string}){
  const [rows,setRows]=useState<NetworkEntity[]>([]),[kind,setKind]=useState<Kind>("track"),[selected,setSelected]=useState<string|null>(null);
  const [id,setId]=useState(""),[body,setBody]=useState(""),[error,setError]=useState<string|null>(null),[saved,setSaved]=useState<NetworkEntity|null>(null),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
  useEffect(()=>{let live=true;void api<{items:NetworkEntity[]}>("/network").then(page=>{if(live)setRows(page.items)}).catch(cause=>{if(live)setError(messageFor(cause))});return()=>{live=false}},[version]);
  const active=rows.find(item=>item.id===selected)??null,visible=rows.filter(item=>item.kind===kind);
  function choose(item:NetworkEntity){setSelected(item.id);setKind(item.kind);setId(item.id);const data=Object.fromEntries(Object.entries(item).filter(([key])=>!['id','kind','revision'].includes(key)));setBody(JSON.stringify(data,null,2));setError(null);setSaved(null)}
  function newEntity(){setSelected(null);setId("");setBody("");setError(null);setSaved(null)}
  async function submit(event:FormEvent){event.preventDefault();setError(null);setSaved(null);setBusy(true);try{const data=jsonObject(body);
    const output=await api<NetworkEntity>(`/network/${kind}`,{method:"POST",body:{id:id.trim(),expected_revision:active?.revision??0,data},csrf});
    setSaved(output);setSelected(output.id);setVersion(x=>x+1);
  }catch(cause){setError(cause instanceof Error&&cause.message.startsWith("Enter ")?cause.message:messageFor(cause))}finally{setBusy(false)}}
  return <div className="admin-grid"><section className="panel"><div className="panel-header"><div><h2>Current network register</h2><p>Stations, sections, tracks, assets, electrical zones and restrictions</p></div><strong>{rows.length} entities</strong></div><div className="admin-kind-tabs">{kinds.map(item=><button type="button" key={item} className={kind===item?"selected":""} onClick={()=>{setKind(item);newEntity()}}>{label(item)}</button>)}</div><div className="admin-list">{visible.length?visible.map(item=><button type="button" key={item.id} className={selected===item.id?"selected":""} onClick={()=>choose(item)}><span><strong>{item.id}</strong><small>{item.kind} · revision {item.revision}</small></span><span>{item.kind==="restriction"?String(item.type??"UNKNOWN"):item.kind==="asset"?String(item.department??"UNKNOWN"):item.kind==="track"?String(item.status??"UNKNOWN"):"Inspect"}</span></button>):<DataState title={`No ${kind} records`} detail="No record of this kind exists in the current network register."/>}</div></section>
    <section className="panel"><div className="panel-header"><div><h2>{active?`Inspect ${active.id}`:`New ${kind}`}</h2><p>{active?`Current revision ${active.revision} · save requires this exact revision`:"References must already exist in the network register"}</p></div>{active&&<button className="button button-text" type="button" onClick={newEntity}>New record</button>}</div><div className="admin-context"><strong>Required fields</strong><span>{schemas[kind]}</span>{active&&<StatusBadge value="CURRENT_REGISTER"/>}</div><form className="admin-form" onSubmit={submit}><label className="field">Entity ID<input value={id} onChange={e=>setId(e.target.value)} disabled={!!active||!canWrite} maxLength={100} pattern="[A-Za-z0-9_-]+" required/></label><label className="field admin-wide">{active?"Edit current data":"Enter complete data"}<textarea value={body} onChange={e=>setBody(e.target.value)} rows={11} spellCheck={false} readOnly={!canWrite} placeholder="No operational facts are prefilled." required/></label>{error&&<div className="inline-alert admin-wide" role="alert">{error}</div>}{saved&&<div className="admin-success admin-wide"><StatusBadge value="SAVED"/><span>{saved.id} · revision {saved.revision}</span></div>}{canWrite?<button className="button button-primary" disabled={busy||!id.trim()||!body.trim()}>{busy?"Saving…":"Save network revision"}</button>:<p className="quiet-note admin-wide">Your role can inspect network configuration. ADMIN or PLANNER can save revisions.</p>}</form></section></div>;
}

function ResourcePanel({canWrite,csrf}:{canWrite:boolean;csrf:string}){
  const [rows,setRows]=useState<Resource[]>([]),[next,setNext]=useState<number|null>(null),[selected,setSelected]=useState(""),[profile,setProfile]=useState<Rule|null>(null);
  const [id,setId]=useState(""),[type,setType]=useState(""),[department,setDepartment]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[mode,setMode]=useState("SIMULATED");
  const [editor,setEditor]=useState(""),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
  async function load(offset=0){try{const page=await api<Page<Resource>>(`/resources?limit=200&offset=${offset}`);setRows(old=>offset?[...old,...page.items]:page.items);setNext(page.next_offset??null)}catch(cause){setError(messageFor(cause))}}
  useEffect(()=>{void load()},[version]);
  useEffect(()=>{if(!selected){setProfile(null);setEditor("");return}let live=true;setProfile(null);setEditor("");void api<Page<Rule>>(`/coordination-rules?kind=RESOURCE_PROFILE&key=${encodeURIComponent(selected)}&limit=1`).then(page=>{if(live){const rule=page.items[0]??null;setProfile(rule);setEditor(rule?JSON.stringify(rule.data,null,2):"")}}).catch(cause=>{if(live)setError(messageFor(cause))});return()=>{live=false}},[selected,version]);
  async function create(event:FormEvent){event.preventDefault();setBusy(true);setError(null);setNotice("");try{const payload={id:id.trim(),resource_type:type.trim(),department:department||null,available_start:start,available_end:end,source_mode:mode};const saved=await api<Resource>("/resources",{method:"POST",body:payload,csrf});setNotice(`Saved ${saved.id}. Add its profile before planning uses it.`);setSelected(saved.id);setVersion(x=>x+1)}catch(cause){setError(messageFor(cause))}finally{setBusy(false)}}
  async function saveProfile(event:FormEvent){event.preventDefault();if(!selected)return;setBusy(true);setError(null);setNotice("");try{const data=jsonObject(editor);const rule=await api<Rule>(`/resources/${encodeURIComponent(selected)}/profiles`,{method:"POST",body:{expected_revision:profile?.revision??0,data},csrf});setProfile(rule);setNotice(`Profile ${selected} saved as revision ${rule.revision}. New snapshots capture the latest profile.`);setVersion(x=>x+1)}catch(cause){setError(cause instanceof Error&&cause.message.startsWith("Enter ")?cause.message:messageFor(cause))}finally{setBusy(false)}}
  return <div className="admin-grid"><section className="panel"><div className="panel-header"><div><h2>Named resource units</h2><p>Availability intervals and explicitly declared source mode</p></div><strong>{rows.length}{next!==null?"+":""}</strong></div><div className="admin-list">{rows.length?rows.map(item=><button type="button" key={item.id} className={selected===item.id?"selected":""} onClick={()=>{setSelected(item.id);setError(null);setNotice("")}}><span><strong>{item.id}</strong><small>{item.resource_type} · {item.department??"Shared"} · {item.source_mode}</small></span><span>{dateTimeAt(item.available_start)}<small>to {dateTimeAt(item.available_end)}</small></span></button>):<DataState title="No named resources" detail="A resource unit and a matching versioned profile are needed for candidate allocation."/>}</div>{next!==null&&<div className="load-more"><button className="button button-outline" onClick={()=>void load(next)}>Load more</button></div>}
    {canWrite&&<form className="admin-form admin-resource-create" onSubmit={create}><h3>Register resource</h3><label className="field">Unit ID<input value={id} onChange={e=>setId(e.target.value)} required maxLength={100}/></label><label className="field">Resource type<input value={type} onChange={e=>setType(e.target.value)} required maxLength={60}/></label><label className="field">Department<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Shared</option><option>ENGINEERING</option><option>TRD</option><option>SNT</option></select></label><label className="field">Source mode<select value={mode} onChange={e=>setMode(e.target.value)}><option>SIMULATED</option><option>IMPORTED</option></select></label><label className="field">Available start (ISO with timezone)<input value={start} onChange={e=>setStart(e.target.value)} placeholder="YYYY-MM-DDTHH:mm:ss+05:30" required/></label><label className="field">Available end (ISO with timezone)<input value={end} onChange={e=>setEnd(e.target.value)} placeholder="YYYY-MM-DDTHH:mm:ss+05:30" required/></label><button className="button button-primary" disabled={busy}>Register unit</button></form>}</section>
    <section className="panel"><div className="panel-header"><div><h2>Resource profile</h2><p>Qualifications, calendar, duties, travel base, rest and pool membership</p></div><StatusBadge value={profile?`REVISION_${profile.revision}`:"NO_PROFILE"}/></div>{!selected?<DataState title="Select a resource" detail="Profiles bind to one named unit and must match its source mode."/>:<><div className="admin-context"><strong>{selected}</strong><span>Required: source_mode, rule_reference, departments[], qualifications[], calendar[], home_track, history, duties[], min_rest_minutes, max_duty_minutes_per_24h, pool_id.</span></div><form className="admin-form" onSubmit={saveProfile}><label className="field admin-wide">{profile?"Current profile data":"Complete new profile data"}<textarea value={editor} onChange={e=>setEditor(e.target.value)} rows={17} readOnly={!canWrite} spellCheck={false} placeholder="Provide actual declared profile facts." required/></label>{error&&<div className="inline-alert admin-wide" role="alert">{error}</div>}{notice&&<div className="admin-success admin-wide">{notice}</div>}{canWrite?<button className="button button-primary" disabled={busy||!editor.trim()}>{busy?"Saving…":`Save profile revision ${profile?profile.revision+1:1}`}</button>:<p className="quiet-note admin-wide">This profile is read only for your role.</p>}</form></>}</section></div>;
}

function PolicyPanel({canWrite,csrf}:{canWrite:boolean;csrf:string}){
  const [rows,setRows]=useState<Rule[]>([]),[next,setNext]=useState<number|null>(null),[key,setKey]=useState(""),[active,setActive]=useState<Rule|null>(null),[body,setBody]=useState("");
  const [error,setError]=useState<string|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
  async function load(offset=0){try{const page=await api<Page<Rule>>(`/coordination-rules?kind=POLICY&limit=200&offset=${offset}`);setRows(old=>offset?[...old,...page.items]:page.items);setNext(page.next_offset??null)}catch(cause){setError(messageFor(cause))}}
  useEffect(()=>{void load()},[version]);
  function choose(rule:Rule){setKey(rule.key);setActive(rule);setBody(JSON.stringify(rule.data,null,2));setError(null);setNotice("")}
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setError(null);setNotice("");try{const data=jsonObject(body);
    const saved=await api<Rule>(`/coordination-policies/${encodeURIComponent(key.trim())}`,{method:"POST",body:{expected_revision:active?.revision??0,data},csrf});
    setActive(saved);setNotice(`Policy ${saved.key} saved as revision ${saved.revision}. New snapshots must explicitly select the intended policy.`);setVersion(x=>x+1);
  }catch(cause){setError(cause instanceof Error&&cause.message.startsWith("Enter ")?cause.message:messageFor(cause))}finally{setBusy(false)}}
  const latest=rows.filter((item,index)=>rows.findIndex(other=>other.key===item.key)===index);
  const editingLatest=!active||active.revision===(rows.find(item=>item.key===active.key)?.revision??active.revision);
  return <div className="admin-grid"><section className="panel"><div className="panel-header"><div><h2>Coordination policies</h2><p>Versioned compatibility, group, travel and resource-pool rules</p></div><strong>{latest.length}{next!==null?"+":""} keys</strong></div><div className="admin-list">{latest.length?latest.map(item=><button type="button" key={item.key} className={active?.key===item.key?"selected":""} onClick={()=>choose(item)}><span><strong>{item.key}</strong><small>Latest loaded revision {item.revision}</small></span><StatusBadge value={String(item.data.source_mode??"UNKNOWN")}/></button>):<DataState title="No coordination policy" detail="Compatibility remains unknown until an explicit policy revision is saved and selected in a snapshot."/>}</div>{next!==null&&<div className="load-more"><button className="button button-outline" onClick={()=>void load(next)}>Load more</button></div>}{active&&<div className="admin-history"><h3>Loaded revision history</h3>{rows.filter(item=>item.key===active.key).map(item=><button key={item.id} type="button" onClick={()=>choose(item)}>r{item.revision} · {shortId(item.id)}</button>)}</div>}</section>
    <section className="panel"><div className="panel-header"><div><h2>{active?`${active.key} · revision ${active.revision}`:"New coordination policy"}</h2><p>Only explicit ALLOW/FORBID rules can decide bundling; unknown pairs remain unknown</p></div>{active&&<button type="button" className="button button-text" onClick={()=>{setKey("");setActive(null);setBody("");setNotice("")}}>New policy</button>}</div><div className="admin-context"><strong>Required policy contract</strong><span>source_mode, rule_reference, pairs[], groups[], travel[], pools[]. Each pair needs work signatures, footprint relation, mode and setup/restoration sharing flags. Group rules must explicitly cover larger bundles.</span></div><form className="admin-form" onSubmit={save}><label className="field">Policy key<input value={key} onChange={e=>setKey(e.target.value)} disabled={!!active||!canWrite} maxLength={100} required/></label><label className="field admin-wide">{active?"Saved policy data":"Enter complete policy data"}<textarea value={body} onChange={e=>setBody(e.target.value)} rows={19} spellCheck={false} readOnly={!canWrite||!editingLatest} placeholder="No compatibility permissions or railway rules are prefilled." required/></label>{!editingLatest&&<p className="quiet-note admin-wide">Historical revision selected. Select the latest revision to edit.</p>}{error&&<div className="inline-alert admin-wide" role="alert">{error}</div>}{notice&&<div className="admin-success admin-wide">{notice}</div>}{canWrite?<button className="button button-primary" disabled={busy||!editingLatest||!key.trim()||!body.trim()}>{busy?"Saving…":`Save policy revision ${active?active.revision+1:1}`}</button>:<p className="quiet-note admin-wide">Your role can inspect policies but cannot revise them.</p>}</form></section></div>;
}

export default function AdministrationPage(){
  const session=useSession(),role=session.value?.user.role??"UNKNOWN",canWrite=role==="ADMIN"||role==="PLANNER";
  const [tab,setTab]=useState<"network"|"resources"|"policies">("network");
  if(role==="DEPARTMENT")return <div className="content-flow"><div className="page-heading"><div><span className="eyebrow">CONFIGURATION</span><h1>Network &amp; Rules</h1></div></div><div className="panel"><DataState title="Configuration access restricted" detail="Department users work through maintenance requirements. Network and coordination configuration is a staff responsibility."/></div></div>;
  return <div className="content-flow admin-page"><div className="page-heading"><div><span className="eyebrow">VERSIONED FACTS · EXPLICIT RULES · AUDITABLE CHANGES</span><h1>Network, Resources &amp; Policies</h1><p>Inspect current infrastructure and configure the named resources and explicit coordination rules captured by future planning snapshots.</p></div><div className="page-actions"><StatusBadge value={canWrite?"CONFIGURATION_EDITOR":"READ_ONLY"}/></div></div><nav className="admin-tabs" aria-label="Administration sections"><button type="button" className={tab==="network"?"selected":""} onClick={()=>setTab("network")}>Network &amp; restrictions</button><button type="button" className={tab==="resources"?"selected":""} onClick={()=>setTab("resources")}>Named resources</button><button type="button" className={tab==="policies"?"selected":""} onClick={()=>setTab("policies")}>Coordination policies</button></nav>{tab==="network"&&<NetworkPanel canWrite={canWrite} csrf={session.value?.csrf_token??""}/>} {tab==="resources"&&<ResourcePanel canWrite={canWrite} csrf={session.value?.csrf_token??""}/>} {tab==="policies"&&<PolicyPanel canWrite={canWrite} csrf={session.value?.csrf_token??""}/>}<div className="readiness-boundary">Current register values and saved rule revisions are configuration evidence. Existing snapshots keep their frozen facts and policy versions. SIMULATED rules require domain review before operational use.</div></div>;
}
