"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import {api,dateAt,dateTimeAt,messageFor,shortId} from "@/lib/api";
import {useSession} from "@/lib/session";
import {useWorkspaceEvidence} from "@/lib/use-workspace";
import {DataState} from "@/components/data-state";
import {StatusBadge} from "@/components/status-badge";
import type {ImportBatchSummary,ImportPreview,ImportResult,Page,SnapshotDetail,SourceRecord} from "@/lib/types";

type Source="TMS"|"SMMS"|"TDMS";
type OperationKind="TRAIN_RUN"|"COA"|"FREIGHT";
const sourceFor={ENGINEERING:"TMS",TRD:"TDMS",SNT:"SMMS"} as const;
const label=(value:string)=>value.replaceAll("_"," ");

function SourceHistory({version}:{version:number}){
  const [batches,setBatches]=useState<ImportBatchSummary[]>([]),[records,setRecords]=useState<SourceRecord[]>([]);
  const [source,setSource]=useState<"ALL"|Source>("ALL"),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError(null);const suffix=source==="ALL"?"":`?source=${source}`;
    void Promise.all([api<Page<ImportBatchSummary>>(`/imports${suffix}`,{signal:controller.signal}),api<Page<SourceRecord>>(`/source-records${suffix}`,{signal:controller.signal})])
      .then(([imports,lineage])=>{setBatches(imports.items);setRecords(lineage.items)}).catch(cause=>{if(!controller.signal.aborted)setError(messageFor(cause))})
      .finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[source,version]);
  return <div className="readiness-history-grid"><section className="panel"><div className="panel-header"><div><h2>Maintenance import outcomes</h2><p>Persisted preview hash and commit result; submitted row bodies are not repeated here</p></div><label className="field compact-field">Source<select value={source} onChange={e=>setSource(e.target.value as "ALL"|Source)}><option value="ALL">All visible sources</option><option>TMS</option><option>TDMS</option><option>SMMS</option></select></label></div>
    {error&&<div className="inline-alert" role="alert">{error}</div>}{loading?<DataState title="Loading import evidence" detail="Reading role-scoped persisted outcomes…"/>:batches.length?<div className="readiness-card-list">{batches.map(item=><article key={item.id}><div><StatusBadge value={item.state}/><strong>{item.source}</strong><span>{shortId(item.id)}</span></div><small>Hash {shortId(item.hash)} · {item.valid_count} valid · {item.error_count} quarantined row(s)</small>{item.result?<p>{item.result.applied} applied · {item.result.duplicates} duplicate · {item.result.quarantined} quarantined</p>:<p>Preview exists; no committed result is recorded.</p>}</article>)}</div>:<DataState title="No visible import batches" detail="A department preview will appear here after backend validation."/>}</section>
    <section className="panel"><div className="panel-header"><div><h2>Source revision lineage</h2><p>External identity, accepted revision and payload hash bound to each request</p></div><strong>{records.length}</strong></div>{loading?<DataState title="Loading source lineage" detail="Reading accepted source revisions…"/>:records.length?<div className="readiness-table-scroll"><table className="readiness-table"><thead><tr><th>Source identity</th><th>Department</th><th>Revision</th><th>R-MAPS request</th><th>Payload hash</th></tr></thead><tbody>{records.map(item=><tr key={item.id}><td><strong>{item.external_id}</strong><small>{item.source}</small></td><td>{item.department}</td><td>r{item.source_revision}</td><td>{shortId(item.request_id)}</td><td><code>{shortId(item.payload_hash)}</code></td></tr>)}</tbody></table></div>:<DataState title="No accepted source records" detail="Committed imported requests will retain their source identity and revision here."/>}</section></div>;
}

function MaintenanceImport({onChanged}:{onChanged:()=>void}){
  const session=useSession();const department=session.value?.user.department;
  const source=department?sourceFor[department]:null;
  const [format,setFormat]=useState<"JSON"|"CSV">("JSON"),[text,setText]=useState(""),[preview,setPreview]=useState<ImportPreview|null>(null),[result,setResult]=useState<ImportResult|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  async function validate(event:FormEvent){event.preventDefault();if(!source||!session.value)return;setBusy(true);setError(null);setResult(null);
    try{let body:Record<string,unknown>={source};if(format==="JSON"){const rows=JSON.parse(text);if(!Array.isArray(rows))throw new Error("JSON input must be an array of request rows.");body={...body,rows}}else body={...body,csv_text:text};
      setPreview(await api<ImportPreview>("/imports/preview",{method:"POST",body,csrf:session.value.csrf_token}));onChanged();
    }catch(cause){setPreview(null);setError(cause instanceof SyntaxError?"JSON could not be parsed. Provide one array of request row objects.":cause instanceof Error&&cause.message.startsWith("JSON input")?cause.message:messageFor(cause))}finally{setBusy(false)}}
  async function commit(){if(!preview||!session.value)return;setBusy(true);setError(null);try{setResult(await api<ImportResult>(`/imports/${preview.id}/commit`,{method:"POST",body:{expected_hash:preview.hash},csrf:session.value.csrf_token}));onChanged()}catch(cause){setError(messageFor(cause))}finally{setBusy(false)}}
  if(!source)return <div className="panel"><DataState title="Department credential required" detail="Maintenance batch import is restricted to the signed-in Engineering, TRD or S&T department."/></div>;
  return <div className="readiness-import-grid"><section className="panel"><div className="panel-header"><div><h2>{source} maintenance request import</h2><p>{department} scope is enforced by the backend</p></div><StatusBadge value="IMPORTED"/></div><form className="readiness-editor" onSubmit={validate}><div className="readiness-format"><label><input type="radio" checked={format==="JSON"} onChange={()=>setFormat("JSON")}/> JSON rows</label><label><input type="radio" checked={format==="CSV"} onChange={()=>setFormat("CSV")}/> CSV text</label></div><label className="field">{format==="JSON"?"Array of source request rows":"CSV with request fields"}<textarea value={text} onChange={e=>{setText(e.target.value);setPreview(null);setResult(null)}} rows={15} spellCheck={false} placeholder={format==="JSON"?"Paste a JSON array. Each row must include external_id, source_revision and the complete request fields.":"Paste a header row and request records. Structured fields use JSON text."} required/></label><p className="readiness-help">R-MAPS overwrites <code>source_mode</code> as IMPORTED. Source/department mismatches, invalid identities and invalid maintenance fields are quarantined by the backend.</p>{error&&<div className="inline-alert" role="alert">{error}</div>}<button className="button button-primary" disabled={busy||!text.trim()}>{busy?"Checking…":"Preview and validate"}</button></form></section>
    <section className="panel"><div className="panel-header"><div><h2>Validated preview</h2><p>Commit is bound to this exact backend-generated content hash</p></div>{preview&&<StatusBadge value={preview.errors.length?"PARTIAL":"VALID"}/>}</div>{!preview?<DataState title="No preview yet" detail="Paste source data and run validation. Nothing is applied during preview."/>:<div className="readiness-preview"><div className="readiness-summary"><div><span>Valid rows</span><strong>{preview.valid.length}</strong></div><div><span>Row errors</span><strong>{preview.errors.length}</strong></div><div><span>Preview hash</span><code>{shortId(preview.hash)}</code></div></div>{preview.errors.length>0&&<div className="readiness-errors">{preview.errors.map(item=><p key={`${item.row}-${item.code}`}><strong>Row {item.row} · {item.code}</strong><span>{item.message}</span></p>)}</div>}<div className="readiness-valid-list">{preview.valid.map(item=><div key={`${item.external_id}-${item.source_revision}`}><strong>{item.external_id}</strong><span>r{item.source_revision} · {item.data.issue_type} · {item.data.footprint.join(", ")}</span></div>)}</div><p className="readiness-help">Commit applies valid rows and records invalid rows as quarantined. Retrying this same batch and hash is idempotent.</p><button type="button" className="button button-primary" disabled={busy||preview.valid.length===0||!!result} onClick={()=>void commit()}>{result?"Committed":"Commit valid rows"}</button>{result&&<div className="readiness-result"><StatusBadge value="COMMITTED"/><strong>{result.applied} applied</strong><span>{result.duplicates} duplicate · {result.quarantined} quarantined</span><small>{result.request_ids.length?`Requests: ${result.request_ids.map(id=>shortId(id)).join(", ")}`:"No new request IDs created"}</small></div>}</div>}</section></div>;
}

function OperationalIntake({role}:{role:string}){
  const session=useSession();const allowed=role==="ADMIN"||role==="PLANNER"||role==="CONTROLLER";
  const [kind,setKind]=useState<OperationKind>(role==="CONTROLLER"?"COA":"TRAIN_RUN"),[text,setText]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[result,setResult]=useState<Record<string,unknown>|null>(null);
  const endpoints={TRAIN_RUN:"/operations/train-runs",COA:"/operations/coa-windows",FREIGHT:"/operations/freight-forecasts"};
  const hints={TRAIN_RUN:"train_id, train_name, train_type, service_date, source_mode, source_revision, occupancies[]",COA:"external_id, source_revision, track_id, start_at, end_at, source_mode",FREIGHT:"COA fields plus issued_at, expected_count, confidence and uncertainty_semantics"};
  async function submit(event:FormEvent){event.preventDefault();if(!session.value)return;setBusy(true);setError(null);setResult(null);try{const body=JSON.parse(text);if(!body||Array.isArray(body)||typeof body!=="object")throw new Error("Operational input must be one JSON object.");setResult(await api<Record<string,unknown>>(endpoints[kind],{method:"POST",body,csrf:session.value.csrf_token}))}catch(cause){setError(cause instanceof SyntaxError?"JSON could not be parsed.":cause instanceof Error&&cause.message.startsWith("Operational input")?cause.message:messageFor(cause))}finally{setBusy(false)}}
  if(!allowed)return <div className="panel"><DataState title="Read-only operational sources" detail="Your role can inspect snapshot provenance but cannot submit timetable, COA or freight source revisions."/></div>;
  return <section className="panel"><div className="panel-header"><div><h2>Operational source intake</h2><p>Typed, revision-checked prototype adapters; no live railway connection is claimed</p></div><StatusBadge value="SOURCE_REVISION_REQUIRED"/></div><form className="readiness-operation" onSubmit={submit}><label className="field">Source record type<select value={kind} onChange={e=>{setKind(e.target.value as OperationKind);setText("");setResult(null)}}><option value="TRAIN_RUN" disabled={role==="CONTROLLER"}>Dated train run and section occupancy</option><option value="COA">COA window</option><option value="FREIGHT">Freight forecast envelope</option></select></label><div className="readiness-schema"><span>Required contract</span><code>{hints[kind]}</code></div><label className="field readiness-operation-json">One complete JSON object<textarea rows={14} value={text} onChange={e=>{setText(e.target.value);setResult(null)}} spellCheck={false} placeholder="Paste the source record. R-MAPS does not prefill operational facts." required/></label>{error&&<div className="inline-alert" role="alert">{error}</div>}<div className="readiness-operation-actions"><button className="button button-primary" disabled={busy||!text.trim()}>{busy?"Submitting…":"Validate and save revision"}</button><span>Initial train times remain fixed. Conflicting or stale revisions are rejected.</span></div>{result&&<div className="readiness-result"><StatusBadge value={result.duplicate?"DUPLICATE":"SAVED"}/><strong>{shortId(String(result.id??""))}</strong><pre>{JSON.stringify(result,null,2)}</pre></div>}</form></section>;
}

function StaffReadiness(){
  const data=useWorkspaceEvidence();const [detail,setDetail]=useState<SnapshotDetail|null>(null),[coverage,setCoverage]=useState<{complete:boolean;gaps:Array<{track_id:string;source:string;status:string}>}|null>(null),[error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!data.selection.snapshotId){setDetail(null);setCoverage(null);return}const controller=new AbortController();setError(null);const id=data.selection.snapshotId;
    void api<SnapshotDetail>(`/snapshots/${id}`,{signal:controller.signal}).then(snapshot=>{if(controller.signal.aborted)return;setDetail(snapshot);const query=new URLSearchParams({start:snapshot.manifest.horizon_start,end:snapshot.manifest.horizon_end});snapshot.manifest.track_ids.forEach(track=>query.append("track_id",track));return api<{complete:boolean;gaps:Array<{track_id:string;source:string;status:string}>}>(`/operations/coverage?${query}`,{signal:controller.signal})}).then(value=>{if(value&&!controller.signal.aborted)setCoverage(value)}).catch(cause=>{if(!controller.signal.aborted)setError(messageFor(cause))});return()=>controller.abort()},[data.selection.snapshotId]);
  const context=detail?.manifest.validation_context,counts=detail?.manifest.counts??{};
  const sourceRows=useMemo(()=>{if(!detail)return[];const facts=detail.manifest.facts;return [
    ...facts.occupancy.map(x=>({kind:"Train occupancy",identity:String(x.train_id??x.id),track:String(x.track_id??"—"),revision:typeof x.source_revision==="number"?x.source_revision:null,mode:String(x.source_mode??"UNKNOWN")})),
    ...facts.coa.map(x=>({kind:"COA",identity:String(x.external_id??x.id),track:String(x.track_id??"—"),revision:typeof x.source_revision==="number"?x.source_revision:null,mode:String(x.source_mode??"UNKNOWN")})),
    ...facts.freight.map(x=>({kind:"Freight forecast",identity:String(x.external_id??x.id),track:String(x.track_id??"—"),revision:typeof x.source_revision==="number"?x.source_revision:null,mode:String(x.source_mode??"UNKNOWN")}))];},[detail]);
  return <div className="content-flow"><div className="planning-context panel"><label className="field">Planning snapshot<select value={data.selection.snapshotId??""} onChange={e=>data.selectSnapshot(e.target.value||null)}><option value="">Select a snapshot</option>{data.snapshots.map(item=><option key={item.id} value={item.id}>{item.source_scope} · {dateAt(item.horizon_start)} · {shortId(item.id)}</option>)}</select></label><div className="context-stamp"><span>Planning horizon</span><strong>{detail?`${dateTimeAt(detail.manifest.horizon_start)} → ${dateTimeAt(detail.manifest.horizon_end)}`:"Not selected"}</strong><small>{detail?.manifest.track_ids.join(", ")??"No track scope"}</small></div><div className="context-stamp"><span>Source authority</span><strong>{context?.scope??data.snapshot?.source_scope??"UNKNOWN"}</strong><small>{context?`Rule ${context.rule_reference}`:"Validation declaration missing"}</small></div><div className="context-stamp"><span>Current workspace state</span><strong>{data.view?.source_state??"NOT LOADED"}</strong><small>{data.view?.current_blockers.length?`${data.view.current_blockers.length} blocker(s)`:"No current blocker reported"}</small></div></div>
    {(data.error||error)&&<div className="inline-alert" role="alert">{data.error??error}</div>}{!detail?<div className="panel"><DataState title={data.loading?"Loading snapshots":"Select a planning snapshot"} detail="Readiness is reported from immutable snapshot facts and declarations; it is never inferred from screen defaults."/></div>:<><div className="readiness-state-strip panel"><div><span>Snapshot hash</span><code>{shortId(detail.content_hash)}</code><small>Created {dateTimeAt(detail.created_at)}</small></div><div><span>Declared valid until</span><strong>{context?dateTimeAt(context.valid_until):"UNKNOWN"}</strong><StatusBadge value={!context?"MISSING":new Date(context.valid_until)>new Date()?"CURRENT":"STALE"}/></div><div><span>COA semantics</span><strong>{context?.coa_semantics??"UNKNOWN"}</strong><small>{context?`${context.clearance_before_minutes} min before · ${context.clearance_after_minutes} min after`:"No declared margins"}</small></div><div><span>Freight policy</span><strong>{context?context.protect_freight_envelope?"Protected envelope":"Not protected":"UNKNOWN"}</strong><small>{detail.manifest.require_freight_forecast?"Forecast required":"Forecast optional"}</small></div><div><span>Live occupancy + COA presence</span><StatusBadge value={coverage?coverage.complete?"COMPLETE":"GAPS":"NOT_CHECKED"}/><small>This check does not certify freight or authority.</small></div></div>
      <div className="readiness-main-grid"><section className="panel"><div className="panel-header"><div><h2>Declared source coverage</h2><p>Snapshot-bound completeness and evidence references</p></div><strong>{context?.coverage.length??0}</strong></div>{context?.coverage.length?<div className="readiness-table-scroll"><table className="readiness-table"><thead><tr><th>Source</th><th>Track</th><th>Coverage interval</th><th>Declaration</th><th>Evidence reference</th></tr></thead><tbody>{context.coverage.map((item,index)=><tr key={`${item.source}-${item.track_id}-${index}`}><td>{item.source}</td><td>{item.track_id??"Corridor-wide"}</td><td>{dateTimeAt(item.start_at)}<small>to {dateTimeAt(item.end_at)}</small></td><td><StatusBadge value={item.complete?"COMPLETE":"INCOMPLETE"}/></td><td>{item.evidence_reference}</td></tr>)}</tbody></table></div>:<DataState title="Coverage declaration missing" detail="Critical source completeness is UNKNOWN. Review or approval must remain blocked."/>}</section><aside className="readiness-side"><section className="panel"><div className="panel-header"><div><h2>Current blockers</h2><p>Live source and validation usability</p></div><StatusBadge value={data.view?.source_state??"UNKNOWN"}/></div><div className="readiness-blockers">{data.view?.current_blockers.length?data.view.current_blockers.map(item=><p key={item}>{label(item)}</p>):<p>{data.view?"No blocker reported by the current workspace projection.":"Workspace evidence not loaded."}</p>}{coverage?.gaps.map(item=><p key={`${item.track_id}-${item.source}`}>{item.track_id} · {item.source} presence {item.status}</p>)}</div></section><section className="panel"><div className="panel-header"><div><h2>Frozen fact counts</h2><p>Counts in this immutable manifest</p></div></div><div className="readiness-counts">{Object.entries(counts).map(([key,value])=><div key={key}><span>{label(key)}</span><strong>{value}</strong></div>)}</div></section></aside></div>
      <section className="panel"><div className="panel-header"><div><h2>Operational source revisions in snapshot</h2><p>Effective records actually frozen into this planning state</p></div><strong>{sourceRows.length}</strong></div>{sourceRows.length?<div className="readiness-table-scroll"><table className="readiness-table"><thead><tr><th>Fact type</th><th>Source identity</th><th>Track</th><th>Mode</th><th>Revision</th></tr></thead><tbody>{sourceRows.map((item,index)=><tr key={`${item.kind}-${item.identity}-${index}`}><td>{item.kind}</td><td>{item.identity}</td><td>{item.track}</td><td><StatusBadge value={String(item.mode??"UNKNOWN")}/></td><td>{item.revision===null?"UNKNOWN":`r${item.revision}`}</td></tr>)}</tbody></table></div>:<DataState title="No operational source facts" detail="This snapshot contains no occupancy, COA or freight records."/>}</section></>}</div>;
}

export default function DataReadinessPage(){
  const session=useSession();const role=session.value?.user.role??"UNKNOWN",staff=role!=="DEPARTMENT";
  const [tab,setTab]=useState(staff?"readiness":"maintenance"),[historyVersion,setHistoryVersion]=useState(0);
  const tabs=staff?[{id:"readiness",label:"System readiness"},{id:"operations",label:"Operational intake"},{id:"history",label:"Import & lineage"}]:[{id:"maintenance",label:"Maintenance import"},{id:"history",label:"Import & lineage"}];
  return <div className="content-flow data-readiness-page"><div className="page-heading"><div><span className="eyebrow">SOURCE INTAKE · PROVENANCE · FAIL-CLOSED READINESS</span><h1>Data Import &amp; System Readiness</h1><p>Validate source revisions, inspect immutable planning evidence and keep unknown operational facts visible.</p></div><div className="page-actions"><span className="prototype-tag">{role} scope</span></div></div><nav className="readiness-tabs" aria-label="Data and readiness sections">{tabs.map(item=><button key={item.id} type="button" className={tab===item.id?"selected":""} onClick={()=>setTab(item.id)}>{item.label}</button>)}</nav>{tab==="readiness"&&staff&&<StaffReadiness/>}{tab==="operations"&&staff&&<OperationalIntake role={role}/>} {tab==="maintenance"&&!staff&&<MaintenanceImport onChanged={()=>setHistoryVersion(x=>x+1)}/>} {tab==="history"&&<SourceHistory version={historyVersion}/>}<div className="readiness-boundary">R-MAPS validates and freezes prototype planning inputs. It does not connect to live railway control systems or grant operational authority.</div></div>;
}
