"""Verify M16 restoration/remaining-work evidence on a dedicated test database."""
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
from datetime import datetime,timezone
import xml.etree.ElementTree as ET

root=Path(__file__).resolve().parents[1]
os.chdir(root)
evidence=root/'docs/evidence'
port=int(os.environ.get('RAILSYNC_TEST_PORT','55432'))
credential=json.loads((root/'.local/db.json').read_text())
env={**os.environ,'PYTHONPATH':'backend','RAILSYNC_DATABASE_URL':
    f"postgresql+psycopg://railsync:{credential['password']}@127.0.0.1:{port}/railsync_test",
    'RAILSYNC_M16_RESTORATION_EVIDENCE_OUTPUT':str(evidence/'M16-restoration-backend-example.json')}
commands=[[sys.executable,'-m','alembic','upgrade','head'],
    [sys.executable,'-m','pytest','-q','-p','no:cacheprovider',f'--junitxml={evidence}/M16-restoration.xml']]
outputs=[]
for command in commands:
    result=subprocess.run(command,env=env,capture_output=True,text=True)
    outputs.append('Command: '+' '.join(command)+'\n'+result.stdout+result.stderr)
    print(outputs[-1],flush=True)
    if result.returncode:
        (evidence/'M16-restoration-failed-output.txt').write_text('\n'.join(outputs),encoding='utf-8')
        raise SystemExit(result.returncode)
cases=ET.parse(evidence/'M16-restoration.xml').findall('.//testcase')
if not cases or any(c.find(t) is not None for c in cases for t in ('failure','error','skipped')):
    raise SystemExit('Incomplete test evidence')
example=json.loads((evidence/'M16-restoration-backend-example.json').read_text(encoding='utf-8'))
assert example['release']['result']['reservation_released'] is True
assert example['release']['result']['scope']=='SIMULATED'
assert example['release']['result']['railway_control_issued'] is False
assert example['snapshot']['manifest']['facts']['requests'][0]['payload']['work_minutes']==40
assert example['optimized']['result']['counts']['scheduled']==example['baseline']['result']['counts']['scheduled']==1
assert example['validation']['status']=='PASS' and example['validation']['usable_for_review']
sources={str(p.relative_to(root)):hashlib.sha256(p.read_bytes()).hexdigest()
    for folder in ('backend','migrations','tests','scripts') for p in (root/folder).rglob('*.py')}
(evidence/'M16-restoration-sources.json').write_text(json.dumps(sources,indent=2),encoding='utf-8')
(evidence/'M16-restoration-test-output.txt').write_text('\n'.join(outputs),encoding='utf-8')
record=f'''# M16 remaining work and restoration — verified slice

Recorded: {datetime.now(timezone.utc).isoformat()}

**{len(cases)} cumulative tests passed** against PostgreSQL railsync_test on localhost:{port}.
Command: set `RAILSYNC_TEST_PORT={port}`, then `.venv/Scripts/python.exe scripts/check_m16_restoration.py`.
Exact commands/results: M16-restoration-test-output.txt and M16-restoration.xml.
Source SHA256 hashes: M16-restoration-sources.json. No Git commit is claimed.

Backend example: M16-restoration-backend-example.json, generated by actual API, baseline, CP-SAT and independent validator code from explicitly synthetic observations.
Expected and asserted: TRD completed; ENG interrupted then explicitly reconciled to 40 work minutes with separate 5-minute restart setup/restoration; whole possession restored and its matched SIMULATED reservation released once; completed TRD omitted from pending demand; both planners schedule exactly one residual request; independent validation PASS. Source deadline and mandatory flag are preserved. No railway command or operational reservation release is issued.

Additional evidence covers roles, version/hash guards, obsolete assessments, concurrent release idempotency, immutable rows, missing/active bundle members, restoration timing, UTC serialization, resource rest/rolling duty with conservative observed-possession history, completed/restored predecessor dependencies, and deliberate residual/history/restoration corruption.

Local environment: Windows denied localhost:55432; localhost:{port} was verified available. The local database helper now supports RAILSYNC_LOCAL_DB_PORT. PostgreSQL completed recovery without SQL edits or WAL reset before testing.

M16 remains incomplete. Resuming within an unreleased possession still requires reconciliation; this slice supports stopped work after verified restoration/release. Replacement approval/execution continuation, source-event reconciliation, replacement differences/lineage and atomic supersession remain pending. M17 must not start.
'''
(evidence/'M16-restoration.md').write_text(record,encoding='utf-8')
print('Restoration/remaining-work slice verified; full M16 remains incomplete.')
