"use client";

import {useEffect,useMemo,useState} from "react";
import {ApiError,api,dateAt,dateTimeAt,messageFor,shortId,timeAt} from "@/lib/api";
import {useSession} from "@/lib/session";
import {useWorkspaceEvidence} from "@/lib/use-workspace";
import {DataState} from "@/components/data-state";
import {DepartmentBadge,StatusBadge} from "@/components/status-badge";
import type {Candidate,ExecutionRecord,ExecutionRecordList,ExecutionRevision,FreezeContext,RevisionDifference,SavedExecutionArtifact} from "@/lib/types";

type Context={revision:ExecutionRevision;freeze:FreezeContext;records:ExecutionRecord[];lineageRecords:ExecutionRecord[];difference:RevisionDifference|null};
type Pending={kind:string;path:string;body:Record<string,unknown>};
const label=(value:string)=>value.replaceAll("_"," ");
const localValue=(value:string)=>{const d=new Date(value);if(Number.isNaN(d.getTime()))return "";const shifted=new Date(d.getTime()-d.getTimezoneOffset()*60000);return shifted.toISOString().slice(0,16)};
const iso=(value:string)=>{const d=new Date(value);if(Number.isNaN(d.getTime()))throw new Error("Enter a valid date and time.");return d.toISOString()};
const latestFor=(records:ExecutionRecord[],requestId:string)=>records.filter(x=>x.request_id===requestId).sort((a,b)=>b.sequence-a.sequence)[0]??null;
const transitions=(status:ExecutionRecord["status"]|null|undefined):ExecutionRecord["status"][]=>status?({STARTED:["INTERRUPTED","COMPLETED"],INTERRUPTED:["RESUMED"],RESUMED:["INTERRUPTED","COMPLETED"],COMPLETED:[]}[status] as ExecutionRecord["status"][]):["STARTED"];

function DifferencePanel({difference}:{difference:RevisionDifference|null}){
  if(!difference)return <section className="panel"><div className="panel-header"><div><h2>Revision differences</h2><p>Stored replacement-lineage evidence</p></div></div><DataState title="Original proposal" detail="This revision has no stored replacement difference. No change classification is inferred."/></section>;
  return <section className="panel"><div className="panel-header"><div><h2>Revision differences</h2><p>Descriptive evidence from the saved source and replacement plans</p></div><StatusBadge value={difference.payload.version}/></div>
    <div className="execution-diff-summary"><div><span>Source proposal</span><strong>{shortId(difference.payload.source_plan_revision_id)}</strong></div><div><span>Replacement proposal</span><strong>{shortId(difference.plan_revision_id)}</strong></div><div><span>Capture</span><strong>{shortId(difference.payload.capture_id)}</strong></div><div><span>Classification</span><strong>{Object.entries(difference.payload.counts).map(([k,v])=>`${v} ${label(k)}`).join(" · ")||"No changes"}</strong></div></div>
    <div className="execution-table-scroll"><table className="execution-table"><thead><tr><th>Request</th><th>Change</th><th>Before</th><th>After</th><th>Work shift</th></tr></thead><tbody>{difference.payload.changes.map(change=><tr key={change.request_id}><td><code>{shortId(change.request_id)}</code></td><td><StatusBadge value={change.change}/></td><td>{change.before?<><strong>{dateTimeAt(change.before.work_start)}–{timeAt(change.before.work_end)}</strong><small>{change.before.track_ids.join(", ")} · {change.before.resource_ids.join(", ")||"no named resource"}</small></>:<small>{change.source_deferred_reason?label(change.source_deferred_reason):"Not scheduled"}</small>}</td><td>{change.after?<><strong>{dateTimeAt(change.after.work_start)}–{timeAt(change.after.work_end)}</strong><small>{change.after.track_ids.join(", ")} · {change.after.resource_ids.join(", ")||"no named resource"}</small></>:<small>{change.replacement_deferred_reason?label(change.replacement_deferred_reason):"Not scheduled"}</small>}</td><td>{change.work_start_shift_minutes===null?"N/A":`${change.work_start_shift_minutes>0?"+":""}${change.work_start_shift_minutes} min`}</td></tr>)}</tbody></table></div>
    <div className="execution-authority">This difference explains what changed. It is not a KPI improvement claim or an operating instruction. Evidence hash <code>{shortId(difference.content_hash)}</code>.</div></section>;
}

function BlockPicker({assignments,selected,onSelect,records}:{assignments:Candidate[];selected:string;onSelect:(id:string)=>void;records:ExecutionRecord[]}){
  return <div className="execution-block-list">{assignments.map(item=>{const terminal=item.request_ids.filter(id=>["COMPLETED","INTERRUPTED"].includes(latestFor(records,id)?.status??"")).length;return <button type="button" key={item.id} className={selected===item.id?"selected":""} onClick={()=>onSelect(item.id)}><span><strong>{item.request_ids.length>1?"Integrated possession":"Possession"} · {shortId(item.id)}</strong><small>{item.track_ids.join(", ")} · {dateTimeAt(item.possession_start)}–{timeAt(item.possession_end)}</small></span><span>{terminal}/{item.request_ids.length} terminal</span></button>})}</div>;
}

export default function ExecutionPage(){
  const data=useWorkspaceEvidence();const {value:session}=useSession();const revisionId=data.selection.revisionId;
  const [context,setContext]=useState<Context|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[version,setVersion]=useState(0);
  const [candidateId,setCandidateId]=useState(""),[requestId,setRequestId]=useState("");
  const [status,setStatus]=useState<ExecutionRecord["status"]>("STARTED"),[observedAt,setObservedAt]=useState(""),[remaining,setRemaining]=useState(""),[evidence,setEvidence]=useState(""),[note,setNote]=useState("");
  const [pending,setPending]=useState<Pending|null>(null),[busy,setBusy]=useState(false);
  const [reconcileRevision,setReconcileRevision]=useState("0"),[restartSetup,setRestartSetup]=useState("0"),[restartRestore,setRestartRestore]=useState("0"),[restartAt,setRestartAt]=useState(""),[reconcileEvidence,setReconcileEvidence]=useState("");
  const [reconciliations,setReconciliations]=useState<Record<string,SavedExecutionArtifact>>({}),[reconciliationIds,setReconciliationIds]=useState<Record<string,string>>({});
  const [actualStart,setActualStart]=useState(""),[restorationStart,setRestorationStart]=useState(""),[restoredAt,setRestoredAt]=useState(""),[releaseEvidence,setReleaseEvidence]=useState("");
  const [attest,setAttest]=useState({track:false,electrical:false,signalling:false,resources:false}),[release,setRelease]=useState<SavedExecutionArtifact|null>(null);
  const [openKind,setOpenKind]=useState<"reconciliation"|"release">("reconciliation"),[openId,setOpenId]=useState(""),[opened,setOpened]=useState<SavedExecutionArtifact|null>(null);
  const controller=session?.user.role==="CONTROLLER",scenario=!!data.snapshot?.scenario_id;
  const revisionOptions=data.runs.flatMap(run=>run.revision_ids.map(id=>({id,run})));

  useEffect(()=>{setContext(null);setCandidateId("");setRequestId("");setError(null);setNotice(null);setPending(null);setRelease(null);setReconciliations({});setReconciliationIds({})},[revisionId]);
  useEffect(()=>{if(!revisionId)return;let live=true;setLoading(true);setError(null);
    void (async()=>{const [revision,freeze,recordPage]=await Promise.all([api<ExecutionRevision>(`/plan-revisions/${revisionId}`),api<FreezeContext>(`/plan-revisions/${revisionId}/freeze-context`),api<ExecutionRecordList>(`/plan-revisions/${revisionId}/execution-records`)]);
      let difference:RevisionDifference|null=null;try{difference=await api<RevisionDifference>(`/plan-revisions/${revisionId}/differences`)}catch(cause){if(!(cause instanceof ApiError&&cause.status===404))throw cause}
      let lineageRecords=recordPage.items;if(difference&&difference.payload.source_plan_revision_id!==revisionId){const source=await api<ExecutionRecordList>(`/plan-revisions/${difference.payload.source_plan_revision_id}/execution-records`);lineageRecords=[...source.items,...recordPage.items]}
      if(live){setContext({revision,freeze,records:recordPage.items,lineageRecords,difference});const first=revision.content.assignments?.[0];setCandidateId(current=>current&&revision.content.assignments?.some(x=>x.id===current)?current:first?.id??"")}
    })().catch(cause=>{if(live)setError(messageFor(cause))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[revisionId,version]);

  const assignments=context?.revision.content.assignments??[];
  const assignment=assignments.find(x=>x.id===candidateId)??null;
  const commitment=context?.freeze.commitments.find(x=>x.candidate_id===candidateId&&x.plan_revision_id===revisionId)??null;
  useEffect(()=>{if(!assignment){setRequestId("");return}setRequestId(current=>assignment.request_ids.includes(current)?current:assignment.request_ids[0]??"");setActualStart(localValue(assignment.possession_start));setRestorationStart(localValue(assignment.tasks.reduce((x,t)=>x>t.restore_start?x:t.restore_start,assignment.tasks[0]?.restore_start??assignment.possession_end)));setRestoredAt(localValue(assignment.possession_end))},[assignment]);
  const selectedTask=assignment?.tasks.find(x=>x.request_id===requestId)??null;
  const history=useMemo(()=>context?.lineageRecords.filter(x=>x.request_id===requestId).sort((a,b)=>a.sequence-b.sequence)??[],[context,requestId]);
  const latest=history.at(-1)??null,nextStatuses=transitions(latest?.status);
  const latestId=latest?.id,latestStatus=latest?.status,latestObserved=latest?.observed_at,latestRemaining=latest?.payload.remaining_work_minutes,selectedWorkStart=selectedTask?.work_start;
  useEffect(()=>{setStatus(transitions(latestStatus)[0]??"STARTED");if(selectedWorkStart){const previous=latestObserved?new Date(latestObserved).getTime()+60000:new Date(selectedWorkStart).getTime();setObservedAt(localValue(new Date(previous).toISOString()))}if(latestStatus==="INTERRUPTED"&&latestObserved){setRemaining(latestRemaining?.toString()??"");setRestartAt(localValue(latestObserved))}},[requestId,latestId,latestStatus,latestObserved,latestRemaining,selectedWorkStart]);
  const currentLatest=assignment?.request_ids.map(id=>latestFor(context?.records??[],id))??[];
  const terminalReady=!!assignment&&currentLatest.length===assignment.request_ids.length&&currentLatest.every(x=>x&&["COMPLETED","INTERRUPTED"].includes(x.status));
  const interrupted=currentLatest.filter((x):x is ExecutionRecord=>x?.status==="INTERRUPTED");
  const reconCovered=interrupted.every(x=>!!reconciliationIds[x.request_id]);
  const canWrite=controller&&!scenario&&context?.freeze.scope==="SIMULATED"&&!!commitment&&commitment.blockers.length===0;
  function refresh(){data.refresh();setVersion(x=>x+1)}
  async function post(item:Pending,onSaved:(value:SavedExecutionArtifact|ExecutionRecord)=>void){setBusy(true);setError(null);setNotice(null);setPending(item);try{const saved=await api<SavedExecutionArtifact|ExecutionRecord>(item.path,{method:"POST",csrf:session?.csrf_token,body:item.body,signal:AbortSignal.timeout(20000)});onSaved(saved);setPending(null);refresh()}catch(cause){if(cause instanceof ApiError&&[401,403,409,422].includes(cause.status))setPending(null);else setNotice("Result unconfirmed. Retry the exact saved request; its idempotency key is unchanged.");setError(messageFor(cause))}finally{setBusy(false)}}
  async function submitObservation(){if(!context||!assignment||!selectedTask||!commitment||!session||!requestId||!canWrite||!nextStatuses.includes(status))return;try{const when=iso(observedAt);const [freshFreeze,freshRecords]=await Promise.all([api<FreezeContext>(`/plan-revisions/${revisionId}/freeze-context`),api<ExecutionRecordList>(`/plan-revisions/${revisionId}/execution-records`)]);const freshCommitment=freshFreeze.commitments.find(x=>x.candidate_id===assignment.id&&x.plan_revision_id===revisionId);if(!freshCommitment||freshCommitment.assignment_hash!==commitment.assignment_hash)throw new Error("The active approval or assignment changed. Refresh before recording execution.");let sequence=latestFor(freshRecords.items,requestId)?.sequence??0;if(context.difference){const source=await api<ExecutionRecordList>(`/plan-revisions/${context.difference.payload.source_plan_revision_id}/execution-records`);sequence=Math.max(sequence,latestFor(source.items,requestId)?.sequence??0)}
      const value=status==="COMPLETED"?0:status==="STARTED"?null:Number(remaining);if((status==="INTERRUPTED"||status==="RESUMED")&&(!Number.isInteger(value)||Number(value)<=0))throw new Error(`${status} requires positive remaining work minutes.`);
      const body={idempotency_key:crypto.randomUUID(),decision_id:freshCommitment.decision_id,expected_plan_hash:context.revision.plan_hash,candidate_id:assignment.id,expected_assignment_hash:freshCommitment.assignment_hash,request_id:requestId,expected_sequence:sequence,expected_operational_revision:freshFreeze.operational_revision,status,observed_at:when,remaining_work_minutes:value,verified:true,evidence_reference:evidence.trim(),note:note.trim()};
      if(evidence.trim().length<3||note.trim().length<3)throw new Error("Evidence reference and note must each contain at least 3 characters.");await post({kind:"execution observation",path:`/plan-revisions/${revisionId}/execution-records`,body},saved=>{const record=saved as ExecutionRecord;setNotice(`${record.status} saved at sequence ${record.sequence}. This records an observation and does not authorize work or release the possession.`);setEvidence("");setNote("")})
    }catch(cause){setError(cause instanceof Error?cause.message:messageFor(cause))}}
  async function submitReconciliation(){if(!context||!latest||latest.status!=="INTERRUPTED"||!selectedTask||!session||!canWrite)return;try{const [freshFreeze,freshRecords]=await Promise.all([api<FreezeContext>(`/plan-revisions/${revisionId}/freeze-context`),api<ExecutionRecordList>(`/plan-revisions/${revisionId}/execution-records`)]),fresh=latestFor(freshRecords.items,requestId);if(!fresh||fresh.id!==latest.id)throw new Error("The interruption evidence changed. Refresh before reconciling remaining work.");const minutes=Number(remaining);if(!Number.isInteger(minutes)||minutes<1)throw new Error("Enter positive remaining work minutes.");if(!selectedTask.request_revision)throw new Error("The approved task does not expose its request revision; reconciliation is blocked.");if(reconcileEvidence.trim().length<3)throw new Error("Enter an evidence reference.");const body={idempotency_key:crypto.randomUUID(),execution_record_id:fresh.id,expected_operational_revision:freshFreeze.operational_revision,expected_revision:Number(reconcileRevision),expected_request_revision:selectedTask.request_revision,remaining_work_minutes:minutes,restart_setup_minutes:Number(restartSetup),restart_restore_minutes:Number(restartRestore),earliest_restart_at:iso(restartAt),verified:true,evidence_reference:reconcileEvidence.trim()};await post({kind:"remaining-work reconciliation",path:"/work-reconciliations",body},saved=>{const artifact=saved as SavedExecutionArtifact;setReconciliations(old=>({...old,[requestId]:artifact}));setReconciliationIds(old=>({...old,[requestId]:artifact.id}));setNotice(`Remaining-work assessment ${shortId(artifact.id)} saved. Restoration is still required before handback.`)})}catch(cause){setError(cause instanceof Error?cause.message:messageFor(cause))}}
  async function submitRelease(){if(!context||!assignment||!commitment||!session||!terminalReady||!reconCovered||!Object.values(attest).every(Boolean))return;try{const [freshFreeze,freshRecords]=await Promise.all([api<FreezeContext>(`/plan-revisions/${revisionId}/freeze-context`),api<ExecutionRecordList>(`/plan-revisions/${revisionId}/execution-records`)]),freshCommitment=freshFreeze.commitments.find(x=>x.candidate_id===assignment.id&&x.plan_revision_id===revisionId);if(!freshCommitment||freshCommitment.assignment_hash!==commitment.assignment_hash)throw new Error("The active approval or assignment changed. Refresh before restoration handback.");const latestRecords=assignment.request_ids.map(id=>latestFor(freshRecords.items,id));if(latestRecords.some(x=>!x||!["COMPLETED","INTERRUPTED"].includes(x.status)))throw new Error("Every request needs current COMPLETED or INTERRUPTED evidence.");if(releaseEvidence.trim().length<3)throw new Error("Enter a restoration evidence reference.");const body={idempotency_key:crypto.randomUUID(),decision_id:freshCommitment.decision_id,candidate_id:assignment.id,expected_assignment_hash:freshCommitment.assignment_hash,expected_operational_revision:freshFreeze.operational_revision,expected_execution_ids:Object.fromEntries(latestRecords.map(x=>[x!.request_id,x!.id])),reconciliation_ids:Object.fromEntries(interrupted.map(x=>[x.request_id,reconciliationIds[x.request_id]])),actual_possession_start:iso(actualStart),restoration_started_at:iso(restorationStart),restored_at:iso(restoredAt),verified:true,track_restored:true,electrical_restored:true,signalling_restored:true,all_resources_clear:true,evidence_reference:releaseEvidence.trim()};await post({kind:"possession restoration",path:"/possession-releases",body},saved=>{const artifact=saved as SavedExecutionArtifact;setRelease(artifact);setNotice(`Software restoration record ${shortId(artifact.id)} saved. Railway control authority and physical handback remain external.`)})}catch(cause){setError(cause instanceof Error?cause.message:messageFor(cause))}}
  async function openArtifact(){if(!openId.trim())return;setBusy(true);setError(null);try{setOpened(await api<SavedExecutionArtifact>(`/${openKind==="release"?"possession-releases":"work-reconciliations"}/${openId.trim()}`))}catch(cause){setError(messageFor(cause))}finally{setBusy(false)}}
  const validContext=!!context&&context.revision.id===revisionId&&context.revision.snapshot_id===data.snapshot?.id;

  return <div className="content-flow execution-page"><div className="page-heading"><div><span className="eyebrow">ACTUAL OBSERVATIONS · SOFTWARE HANDOVER RECORD</span><h1>Execution, Restoration &amp; Handback</h1><p>Trace replacement changes, record verified work observations, reconcile interrupted work and close a shared possession only after restoration evidence.</p></div><div className="page-actions"><button className="button button-outline" onClick={refresh} disabled={busy}>Refresh evidence</button></div></div>
    {(data.error||error)&&<div className="inline-alert" role="alert">{data.error??error}</div>}{notice&&<div className={pending?"inline-alert":"inline-success"} role="status">{notice}</div>}
    <div className="planning-context panel"><label className="field">Planning snapshot<select value={data.selection.snapshotId??""} onChange={e=>data.selectSnapshot(e.target.value||null)}><option value="">Select a snapshot</option>{data.snapshots.map(x=><option key={x.id} value={x.id}>{x.source_scope} · {dateAt(x.horizon_start)} · {shortId(x.id)}</option>)}</select></label><label className="field">Approved proposal revision<select value={revisionId??""} disabled={!data.snapshot} onChange={e=>data.selection.selectRevision(e.target.value||null)}><option value="">Select a saved proposal</option>{revisionOptions.map(({id,run})=><option key={id} value={id}>{run.planner_type} · {shortId(id)} · {run.job_status}</option>)}</select></label><div className="context-stamp"><span>Scope</span><strong>{context?.freeze.scope??data.snapshot?.source_scope??"Not selected"}</strong><small>{scenario?"Scenario writes prohibited":"Bound to saved evidence"}</small></div><div className="context-stamp"><span>Signed-in role</span><strong>{session?.user.role??"Unknown"}</strong><small>{controller?"Observation writes available":"Read-only evidence"}</small></div></div>
    {!data.snapshot||!revisionId?<div className="panel"><DataState title="Select a snapshot and proposal" detail="Execution evidence is always bound to one exact approved plan revision."/></div>:!validContext?<div className="panel"><DataState title={loading||data.viewLoading?"Loading execution ledger":"Execution context unavailable"} detail={loading?"Reading approval commitments, observations and replacement evidence…":"Refresh the exact saved proposal before recording observations."}/></div>:<>
      <div className="execution-state-strip panel"><div><span>Proposal</span><strong>{shortId(context.revision.id)} · r{context.revision.revision}</strong></div><div><span>State</span><StatusBadge value={context.revision.current_state.status}/></div><div><span>Operational revision</span><strong>{context.freeze.operational_revision}</strong></div><div><span>Active commitments</span><strong>{context.freeze.commitments.length}</strong></div><div><span>Saved observations</span><strong>{context.records.length}</strong></div><div><span>Authority</span><strong>Observation only</strong></div></div>
      {scenario&&<div className="inline-alert">Isolated what-if scenarios cannot create execution, reconciliation, reservation or release records.</div>}{!controller&&<div className="inline-note">Your role can inspect immutable evidence. A CONTROLLER session is required to append verified observations.</div>}
      <DifferencePanel difference={context.difference}/>
      <div className="execution-grid"><section className="panel"><div className="panel-header"><div><h2>Approved possession ledger</h2><p>Planned work remains distinct from observed work</p></div>{commitment?<StatusBadge value={commitment.frozen?"FROZEN":"ACTIVE"}/>:<StatusBadge value="NO_ACTIVE_COMMITMENT"/>}</div>
        {assignments.length?<BlockPicker assignments={assignments} selected={candidateId} onSelect={setCandidateId} records={context.records}/>:<DataState title="No scheduled assignments" detail="No possession is inferred from an empty proposal."/>}
        {assignment&&<><div className="execution-request-tabs">{assignment.tasks.map(task=>{const record=latestFor(context.records,task.request_id);return <button type="button" key={task.request_id} className={requestId===task.request_id?"selected":""} onClick={()=>setRequestId(task.request_id)}><DepartmentBadge department={task.department}/><span><strong>{task.issue_type}</strong><small>{shortId(task.request_id)} · {record?.status??"NOT STARTED"}</small></span></button>})}</div>
          <div className="execution-plan-band"><span>Setup <strong>{selectedTask?`${timeAt(selectedTask.setup_start)}–${timeAt(selectedTask.setup_end)}`:"—"}</strong></span><span>Work <strong>{selectedTask?`${timeAt(selectedTask.work_start)}–${timeAt(selectedTask.work_end)}`:"—"}</strong></span><span>Restoration <strong>{selectedTask?`${timeAt(selectedTask.restore_start)}–${timeAt(selectedTask.restore_end)}`:"—"}</strong></span><span>Tracks <strong>{assignment.track_ids.join(", ")}</strong></span></div>
          <div className="execution-ledger">{history.length?history.map(record=><article key={record.id}><div><span className="execution-sequence">{record.sequence}</span><StatusBadge value={record.status}/><strong>{dateTimeAt(record.observed_at)}</strong></div><p>{record.payload.note}</p><small>Received {dateTimeAt(record.received_at)} · Evidence: {record.payload.evidence_reference}</small><div className="execution-flags">{record.result.outside_planned_work_interval&&<span>Outside planned interval</span>}{record.result.source_plan_stale&&<span>Source plan stale</span>}{record.result.continuation&&<span>Controlled continuation</span>}<span>Reservation retained</span></div></article>):<DataState title="No observations" detail="A planned task is not a started or completed task."/>}</div></>}
      </section>
      <aside className="execution-side"><section className="panel"><div className="panel-header"><div><h2>Append work observation</h2><p>Verified controller record; never an execution command</p></div></div><div className="execution-form"><label className="field">Next status<select value={nextStatuses.length?status:""} onChange={e=>setStatus(e.target.value as ExecutionRecord["status"])} disabled={!nextStatuses.length}>{!nextStatuses.length&&<option value="">Lifecycle complete</option>}{nextStatuses.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Observed at<input type="datetime-local" value={observedAt} onChange={e=>setObservedAt(e.target.value)}/></label>{status!=="STARTED"&&status!=="COMPLETED"&&<label className="field">Remaining work minutes<input type="number" min="1" value={remaining} onChange={e=>setRemaining(e.target.value)}/></label>}<label className="field execution-wide">Evidence reference<input value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Work log, field report or fixture reference"/></label><label className="field execution-wide">Observation note<textarea rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="What was observed?"/></label><button type="button" className="button" onClick={()=>void submitObservation()} disabled={!canWrite||busy||!!pending||!nextStatuses.length}>Record observation</button>{!commitment&&<p className="quiet-note execution-wide">No active approval commitment matches this assignment. Observation writes remain blocked.</p>}</div></section>
        {latest?.status==="INTERRUPTED"&&<section className="panel"><div className="panel-header"><div><h2>Remaining-work assessment</h2><p>Required before an interrupted request can be released and replanned</p></div>{reconciliations[requestId]&&<StatusBadge value="SAVED"/>}</div><div className="execution-form"><label className="field">Remaining minutes<input type="number" min="1" value={remaining} onChange={e=>setRemaining(e.target.value)}/></label><label className="field">Assessment revision<input type="number" min="0" value={reconcileRevision} onChange={e=>setReconcileRevision(e.target.value)}/></label><label className="field">Restart setup minutes<input type="number" min="0" value={restartSetup} onChange={e=>setRestartSetup(e.target.value)}/></label><label className="field">Restart restore minutes<input type="number" min="0" value={restartRestore} onChange={e=>setRestartRestore(e.target.value)}/></label><label className="field execution-wide">Earliest restart<input type="datetime-local" value={restartAt} onChange={e=>setRestartAt(e.target.value)}/></label><label className="field execution-wide">Evidence reference<input value={reconcileEvidence} onChange={e=>setReconcileEvidence(e.target.value)}/></label><button type="button" className="button" disabled={!canWrite||busy||!!pending} onClick={()=>void submitReconciliation()}>Save assessment</button></div></section>}
      </aside></div>
      {assignment&&<section className="panel"><div className="panel-header"><div><h2>Whole-possession restoration &amp; handback record</h2><p>Every bundled request must be terminal; interruption assessments must be current</p></div><StatusBadge value={release?"RECORDED":terminalReady&&reconCovered?"READY_FOR_EVIDENCE":"BLOCKED"}/></div><div className="execution-release-grid"><div className="execution-release-status">{assignment.request_ids.map(id=>{const current=latestFor(context.records,id);return <div key={id}><code>{shortId(id)}</code><StatusBadge value={current?.status??"NO_OBSERVATION"}/>{current?.status==="INTERRUPTED"?<label>Reconciliation ID<input value={reconciliationIds[id]??""} onChange={e=>setReconciliationIds(old=>({...old,[id]:e.target.value}))}/></label>:<span>{current?`Sequence ${current.sequence}`:"Record execution first"}</span>}</div>})}</div><div className="execution-release-form"><label className="field">Actual possession start<input type="datetime-local" value={actualStart} onChange={e=>setActualStart(e.target.value)}/></label><label className="field">Restoration started<input type="datetime-local" value={restorationStart} onChange={e=>setRestorationStart(e.target.value)}/></label><label className="field">Restored at<input type="datetime-local" value={restoredAt} onChange={e=>setRestoredAt(e.target.value)}/></label><label className="field execution-wide">Restoration evidence<input value={releaseEvidence} onChange={e=>setReleaseEvidence(e.target.value)}/></label><div className="execution-attest execution-wide"><label><input type="checkbox" checked={attest.track} onChange={e=>setAttest({...attest,track:e.target.checked})}/> Track restored</label><label><input type="checkbox" checked={attest.electrical} onChange={e=>setAttest({...attest,electrical:e.target.checked})}/> Electrical state restored</label><label><input type="checkbox" checked={attest.signalling} onChange={e=>setAttest({...attest,signalling:e.target.checked})}/> Signalling restored</label><label><input type="checkbox" checked={attest.resources} onChange={e=>setAttest({...attest,resources:e.target.checked})}/> All resources clear</label></div><button type="button" className="button" onClick={()=>void submitRelease()} disabled={!canWrite||!terminalReady||!reconCovered||!Object.values(attest).every(Boolean)||busy||!!pending}>Record software handback</button></div></div>{release&&<div className="execution-saved"><strong>Saved release {shortId(release.id)}</strong><span>{dateTimeAt(release.created_at)} · reservation_released = {String(release.result.reservation_released)}</span><small>Railway control issued = {String(release.result.railway_control_issued)}. Physical railway authority remains external.</small></div>}</section>}
      <section className="panel"><div className="panel-header"><div><h2>Open saved restoration evidence</h2><p>Read one immutable artifact by its recorded ID</p></div></div><div className="execution-open"><label className="field">Artifact type<select value={openKind} onChange={e=>setOpenKind(e.target.value as typeof openKind)}><option value="reconciliation">Work reconciliation</option><option value="release">Possession release</option></select></label><label className="field">Artifact ID<input value={openId} onChange={e=>setOpenId(e.target.value)} placeholder="UUID"/></label><button type="button" className="button button-outline" disabled={busy||!openId.trim()} onClick={()=>void openArtifact()}>Open evidence</button></div>{opened&&<div className="execution-saved"><strong>{shortId(opened.id)} · {dateTimeAt(opened.created_at)}</strong><span>Payload hash {shortId(opened.payload_hash)}</span><pre>{JSON.stringify({payload:opened.payload,result:opened.result},null,2)}</pre></div>}</section>
      {pending&&<div className="review-pending"><p>The {pending.kind} result is uncertain. Retrying sends the exact saved request and idempotency key.</p><button className="button button-outline" disabled={busy} onClick={()=>void post(pending,saved=>{setNotice(`${pending.kind} saved as ${shortId((saved as SavedExecutionArtifact|ExecutionRecord).id)}.`)})}>Retry exact request</button></div>}
    </>}
  </div>;
}
